/* Reconstructed mnemonic source for tinyxmlparser.o. */
.syntax unified
.arch armv5te

.type FIRST_BYTE_MARK.5676, %object
.type _ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.62, %object
.type _ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.68, %object
.weak _ZNK9TiXmlNode9ToElementEv
.type _ZNK9TiXmlNode9ToElementEv, %function
.weak _ZNK9TiXmlNode9ToCommentEv
.type _ZNK9TiXmlNode9ToCommentEv, %function
.weak _ZNK9TiXmlNode9ToUnknownEv
.type _ZNK9TiXmlNode9ToUnknownEv, %function
.weak _ZNK9TiXmlNode6ToTextEv
.type _ZNK9TiXmlNode6ToTextEv, %function
.weak _ZNK9TiXmlNode13ToDeclarationEv
.type _ZNK9TiXmlNode13ToDeclarationEv, %function
.weak _ZN9TiXmlNode9ToElementEv
.type _ZN9TiXmlNode9ToElementEv, %function
.weak _ZN9TiXmlNode9ToCommentEv
.type _ZN9TiXmlNode9ToCommentEv, %function
.weak _ZN9TiXmlNode9ToUnknownEv
.type _ZN9TiXmlNode9ToUnknownEv, %function
.weak _ZN9TiXmlNode6ToTextEv
.type _ZN9TiXmlNode6ToTextEv, %function
.weak _ZN9TiXmlNode13ToDeclarationEv
.type _ZN9TiXmlNode13ToDeclarationEv, %function
.weak _ZNK13TiXmlDocument10ToDocumentEv
.type _ZNK13TiXmlDocument10ToDocumentEv, %function
.weak _ZN13TiXmlDocument10ToDocumentEv
.type _ZN13TiXmlDocument10ToDocumentEv, %function
.global _ZN9TiXmlBase18ConvertUTF32ToUTF8EmPcPi
.type _ZN9TiXmlBase18ConvertUTF32ToUTF8EmPcPi, %function
.weak _ZNK14TiXmlAttribute5PrintEP7__sFILEi
.type _ZNK14TiXmlAttribute5PrintEP7__sFILEi, %function
.weak _ZN9TiXmlBaseD0Ev
.type _ZN9TiXmlBaseD0Ev, %function
.weak _ZTV9TiXmlBase
.type _ZTV9TiXmlBase, %object
.weak _ZN9TiXmlBaseD1Ev
.type _ZN9TiXmlBaseD1Ev, %function
.global _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
.type _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding, %function
.global _ZN9TiXmlBase13utf8ByteTableE
.type _ZN9TiXmlBase13utf8ByteTableE, %object
.global _ZNK9TiXmlText5BlankEv
.type _ZNK9TiXmlText5BlankEv, %function
.global _ZN9TiXmlBase10IsAlphaNumEh13TiXmlEncoding
.type _ZN9TiXmlBase10IsAlphaNumEh13TiXmlEncoding, %function
.global _ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding
.type _ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding, %function
.weak _ZN14TiXmlAttributeD1Ev
.type _ZN14TiXmlAttributeD1Ev, %function
.global _ZTV14TiXmlAttribute
.type _ZTV14TiXmlAttribute, %object
.global _ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding
.type _ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding, %function
.global _ZN9TiXmlBase6entityE
.type _ZN9TiXmlBase6entityE, %object
.weak _ZN14TiXmlAttributeD0Ev
.type _ZN14TiXmlAttributeD0Ev, %function
.weak _ZN13TiXmlDocumentD0Ev
.type _ZN13TiXmlDocumentD0Ev, %function
.global _ZTV13TiXmlDocument
.type _ZTV13TiXmlDocument, %object
.global _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
.type _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding, %function
.weak _ZN13TiXmlDocumentD1Ev
.type _ZN13TiXmlDocumentD1Ev, %function
.global _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
.type _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding, %function
.global _ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding
.type _ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding, %function
.global _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN12TiXmlComment5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN12TiXmlComment5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN12TiXmlUnknown5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN12TiXmlUnknown5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding
.type _ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding, %function
.global _ZN12TiXmlElement9ReadValueEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN12TiXmlElement9ReadValueEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN12TiXmlElement5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN12TiXmlElement5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN13TiXmlDocument5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN13TiXmlDocument5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding
.type _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding, %function
.global _ZN9TiXmlText5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN9TiXmlText5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function
.global _ZN16TiXmlDeclaration5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
.type _ZN16TiXmlDeclaration5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, %function

.section .text,"ax",%progbits
.balign 4
.thumb
.thumb_func
_ZN9TiXmlBase18ConvertUTF32ToUTF8EmPcPi:
    push {r4, r5, lr}
    adds r4, r2, #0
    cmp r0, #127
    bhi.n .Lsec21_0000001e
    movs r3, #1
    str r3, [r2, #0]
    adds r1, #1
.Lsec21_0000000e:
    ldr r3, [r4, #0]
    ldr r2, [pc, #104]
    lsls r3, r3, #2
    ldr r3, [r3, r2]
    subs r1, #1
    orrs r3, r0
    strb r3, [r1, #0]
.Lsec21_0000001c:
    pop {r4, r5, pc}
.Lsec21_0000001e:
    ldr r3, [pc, #96]
    cmp r0, r3
    bhi.n .Lsec21_0000003c
    movs r3, #2
    str r3, [r2, #0]
    adds r1, #2
.Lsec21_0000002a:
    movs r3, #128
    negs r3, r3
    orrs r3, r0
    movs r2, #64
    subs r1, #1
    bics r3, r2
    lsrs r0, r0, #6
    strb r3, [r1, #0]
    b.n .Lsec21_0000000e
.Lsec21_0000003c:
    ldr r3, [pc, #68]
    cmp r0, r3
    bls.n .Lsec21_0000005e
    ldr r3, [pc, #68]
    cmp r0, r3
    bhi.n .Lsec21_00000076
    movs r3, #4
    str r3, [r2, #0]
    movs r3, #128
    negs r3, r3
    orrs r3, r0
    movs r2, #64
    bics r3, r2
    adds r5, r1, #3
    lsrs r0, r0, #6
    strb r3, [r1, #3]
    b.n .Lsec21_00000064
.Lsec21_0000005e:
    movs r3, #3
    str r3, [r2, #0]
    adds r5, r1, #3
.Lsec21_00000064:
    movs r3, #128
    negs r3, r3
    orrs r3, r0
    movs r2, #64
    subs r1, r5, #1
    bics r3, r2
    lsrs r0, r0, #6
    strb r3, [r1, #0]
    b.n .Lsec21_0000002a
.Lsec21_00000076:
    movs r3, #0
    str r3, [r2, #0]
    b.n .Lsec21_0000001c
    .long .Lsec58_00000470
    .long 0x000007ff
    .long 0x0000ffff
    .long 0x001fffff
.thumb
.thumb_func
_ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, sl
    mov r6, r9
    mov r5, r8
    push {r5, r6, r7}
    adds r7, r0, #0
    mov r8, r1
    mov r9, r2
    cmp r1, #0
    beq.n .Lsec21_0000016c
.Lsec21_000000a0:
    ldr r3, [r7, #12]
    cmp r3, #0
    ble.n .Lsec21_000000ec
    ldr r2, [r7, #0]
    ldr r5, [r7, #8]
    mov sl, r2
    ldr r6, [r7, #4]
    cmp r5, #0
    beq.n .Lsec21_00000178
.Lsec21_000000b2:
    cmp r8, r5
    bls.n .Lsec21_000000d6
.Lsec21_000000b6:
    ldrb r3, [r5, #0]
    cmp r3, #10
    beq.n .Lsec21_0000011e
    cmp r3, #10
    bhi.n .Lsec21_000000f6
    cmp r3, #0
    beq.n .Lsec21_000000ec
    cmp r3, #9
    beq.n .Lsec21_00000150
.Lsec21_000000c8:
    mov r2, r9
    cmp r2, #1
    beq.n .Lsec21_00000140
.Lsec21_000000ce:
    adds r5, #1
    adds r6, #1
    cmp r8, r5
    bhi.n .Lsec21_000000b6
.Lsec21_000000d6:
    mov r3, sl
    str r3, [r7, #0]
    str r6, [r7, #4]
    adds r3, #1
    blt.n .Lsec21_000001a0
.Lsec21_000000e0:
    ldr r3, [r7, #4]
    adds r3, #1
    blt.n .Lsec21_00000192
.Lsec21_000000e6:
    str r5, [r7, #8]
    cmp r5, #0
    beq.n .Lsec21_00000184
.Lsec21_000000ec:
    pop {r2, r3, r4}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    pop {r4, r5, r6, r7, pc}
.Lsec21_000000f6:
    cmp r3, #13
    beq.n .Lsec21_0000012e
    cmp r3, #239
    bne.n .Lsec21_000000c8
    mov r3, r9
    cmp r3, #1
    bne.n .Lsec21_000000ce
    ldrb r3, [r5, #1]
    cmp r3, #0
    beq.n .Lsec21_000000b2
    ldrb r2, [r5, #2]
    cmp r2, #0
    beq.n .Lsec21_000000b2
    cmp r3, #187
    beq.n .Lsec21_000001b0
    cmp r3, #191
    beq.n .Lsec21_000001ac
.Lsec21_00000118:
    adds r5, #3
    adds r6, #1
    b.n .Lsec21_000000b2
.Lsec21_0000011e:
    adds r5, #1
    ldrb r3, [r5, #0]
    movs r2, #1
    add sl, r2
    cmp r3, #13
    beq.n .Lsec21_0000013a
.Lsec21_0000012a:
    movs r6, #0
    b.n .Lsec21_000000b2
.Lsec21_0000012e:
    movs r3, #1
    adds r5, #1
    add sl, r3
    ldrb r3, [r5, #0]
    cmp r3, #10
    bne.n .Lsec21_0000012a
.Lsec21_0000013a:
    adds r5, #1
    movs r6, #0
    b.n .Lsec21_000000b2
.Lsec21_00000140:
    ldr r2, [pc, #116]
    lsls r3, r3, #2
    ldr r3, [r3, r2]
    cmp r3, #0
    beq.n .Lsec21_00000164
    adds r5, r5, r3
    adds r6, #1
    b.n .Lsec21_000000b2
.Lsec21_00000150:
    ldr r4, [r7, #12]
    adds r0, r6, #0
    adds r1, r4, #0
.Lsec21_00000156:
    bl __aeabi_idiv
    adds r0, #1
    adds r6, r0, #0
    muls r6, r4
    adds r5, #1
    b.n .Lsec21_000000b2
.Lsec21_00000164:
    movs r3, #1
    adds r5, r5, r3
    adds r6, #1
    b.n .Lsec21_000000b2
.Lsec21_0000016c:
    ldr r0, [pc, #76]
    ldr r2, [pc, #80]
    movs r1, #198
.Lsec21_00000172:
    bl __assert
    b.n .Lsec21_000000a0
.Lsec21_00000178:
    ldr r0, [pc, #64]
    ldr r2, [pc, #72]
    movs r1, #210
.Lsec21_0000017e:
    bl __assert
    b.n .Lsec21_000000b2
.Lsec21_00000184:
    movs r1, #155
    ldr r0, [pc, #52]
    ldr r2, [pc, #60]
    lsls r1, r1, #1
.Lsec21_0000018c:
    bl __assert
    b.n .Lsec21_000000ec
.Lsec21_00000192:
    movs r1, #154
    ldr r0, [pc, #36]
    ldr r2, [pc, #52]
    lsls r1, r1, #1
.Lsec21_0000019a:
    bl __assert
    b.n .Lsec21_000000e6
.Lsec21_000001a0:
    ldr r0, [pc, #24]
    ldr r2, [pc, #44]
    ldr r1, [pc, #44]
.Lsec21_000001a6:
    bl __assert
    b.n .Lsec21_000000e0
.Lsec21_000001ac:
    cmp r2, #190
    beq.n .Lsec21_000001b4
.Lsec21_000001b0:
    cmp r2, #191
    bne.n .Lsec21_00000118
.Lsec21_000001b4:
    adds r5, #3
    b.n .Lsec21_000000b2
    .long _ZN9TiXmlBase13utf8ByteTableE
    .long .Lsec49_00000004
    .long .Lsec49_00000040
    .long .Lsec49_00000044
    .long .Lsec49_00000070
    .long .Lsec49_0000005c
    .long .Lsec49_00000048
    .long 0x00000133
.thumb
.thumb_func
_ZNK9TiXmlText5BlankEv:
    push {r4, r5, r6, r7, lr}
    ldr r7, [r0, #32]
    sub sp, #4
    ldr r6, [r7, #0]
    cmp r6, #0
    beq.n .Lsec21_00000202
    movs r5, #0
.Lsec21_000001e6:
    adds r3, r7, r5
    ldrb r4, [r3, #8]
    adds r0, r4, #0
.Lsec21_000001ec:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_000001fc
    cmp r4, #10
    beq.n .Lsec21_000001fc
    cmp r4, #13
    bne.n .Lsec21_00000204
.Lsec21_000001fc:
    adds r5, #1
    cmp r6, r5
    bne.n .Lsec21_000001e6
.Lsec21_00000202:
    movs r0, #1
.Lsec21_00000204:
    add sp, #4
    pop {r4, r5, r6, r7, pc}
.thumb_func
_ZN9TiXmlBase10IsAlphaNumEh13TiXmlEncoding:
    push {lr}
    sub sp, #4
    cmp r0, #126
    bls.n .Lsec21_00000216
    movs r0, #1
.Lsec21_00000212:
    add sp, #4
    pop {pc}
.Lsec21_00000216:
    bl isalnum
    b.n .Lsec21_00000212
.thumb_func
_ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding:
    push {lr}
    sub sp, #4
    cmp r0, #126
    bls.n .Lsec21_0000022a
    movs r0, #1
.Lsec21_00000226:
    add sp, #4
    pop {pc}
.Lsec21_0000022a:
    bl isalpha
    b.n .Lsec21_00000226
.thumb_func
_ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    sub sp, #12
    adds r6, r3, #0
    movs r3, #0
    str r2, [sp, #0]
    str r3, [r2, #0]
    str r1, [sp, #4]
    mov sl, r0
    movs r2, #1
    ldrb r3, [r0, #1]
    add r2, sl
    mov r9, r2
    cmp r3, #35
    beq.n .Lsec21_00000296
.Lsec21_00000256:
    ldr r4, [pc, #360]
    ldr r3, [pc, #360]
    movs r7, #0
    mov fp, r3
    mov r8, r4
.Lsec21_00000260:
    ldr r5, [r4, #0]
    ldr r6, [r4, #4]
    adds r0, r5, #0
    mov r1, sl
    adds r2, r6, #0
.Lsec21_0000026a:
    bl strncmp
    cmp r0, #0
    beq.n .Lsec21_000002b2
    movs r3, #12
    adds r7, #1
    add r8, r3
    adds r4, #12
    cmp r7, #5
    bne.n .Lsec21_00000260
    mov r2, sl
    ldrb r3, [r2, #0]
    ldr r2, [sp, #4]
    strb r3, [r2, #0]
.Lsec21_00000286:
    mov r0, r9
    add sp, #12
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000296:
    mov r2, sl
    ldrb r3, [r2, #2]
    adds r0, #2
    cmp r3, #0
    beq.n .Lsec21_00000256
    cmp r3, #120
    bne.n .Lsec21_000002de
    ldrb r3, [r2, #3]
    adds r0, #1
    cmp r3, #0
    bne.n .Lsec21_00000344
.Lsec21_000002ac:
    movs r3, #0
    mov r9, r3
    b.n .Lsec21_00000286
.Lsec21_000002b2:
    adds r0, r5, #0
.Lsec21_000002b4:
    bl strlen
    cmp r6, r0
    beq.n .Lsec21_000002c6
    ldr r0, [pc, #264]
    ldr r1, [pc, #268]
    mov r2, fp
.Lsec21_000002c2:
    bl __assert
.Lsec21_000002c6:
    mov r2, r8
    ldrb r3, [r2, #8]
    ldr r2, [sp, #4]
    strb r3, [r2, #0]
    ldr r2, [sp, #0]
    movs r3, #1
    str r3, [r2, #0]
    mov r2, r8
    ldr r3, [r2, #4]
    add r3, sl
    mov r9, r3
    b.n .Lsec21_00000286
.Lsec21_000002de:
    movs r1, #59
.Lsec21_000002e0:
    bl strchr
    cmp r0, #0
    beq.n .Lsec21_000002ac
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_000002ac
    mov r2, sl
    subs r7, r0, r2
    subs r0, #1
    ldrb r3, [r0, #0]
    cmp r3, #35
    beq.n .Lsec21_000003ba
    adds r2, r3, #0
    subs r2, #48
    lsls r3, r2, #24
    lsrs r3, r3, #24
    cmp r3, #9
    bhi.n .Lsec21_000002ac
    movs r4, #0
    movs r1, #1
    b.n .Lsec21_00000318
.Lsec21_0000030c:
    adds r2, r3, #0
    subs r2, #48
    lsls r3, r2, #24
    lsrs r3, r3, #24
    cmp r3, #9
    bhi.n .Lsec21_000002ac
.Lsec21_00000318:
    adds r3, r1, #0
    muls r3, r2
    adds r4, r4, r3
    lsls r3, r1, #2
    adds r3, r3, r1
    subs r0, #1
    lsls r1, r3, #1
    ldrb r3, [r0, #0]
    cmp r3, #35
    bne.n .Lsec21_0000030c
.Lsec21_0000032c:
    cmp r6, #1
    beq.n .Lsec21_000003ae
    ldr r3, [sp, #4]
    strb r4, [r3, #0]
    ldr r2, [sp, #0]
    movs r3, #1
    str r3, [r2, #0]
.Lsec21_0000033a:
    mov r2, sl
    adds r3, r2, r7
    adds r3, #1
    mov r9, r3
    b.n .Lsec21_00000286
.Lsec21_00000344:
    movs r1, #59
.Lsec21_00000346:
    bl strchr
    cmp r0, #0
    beq.n .Lsec21_000002ac
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_000002ac
    mov r3, sl
    subs r7, r0, r3
    subs r0, #1
    ldrb r2, [r0, #0]
    cmp r2, #120
    beq.n .Lsec21_000003ba
    movs r4, #0
    movs r5, #1
    b.n .Lsec21_00000376
.Lsec21_00000366:
    adds r3, r1, #0
    muls r3, r5
    adds r4, r4, r3
.Lsec21_0000036c:
    subs r0, #1
    ldrb r2, [r0, #0]
    cmp r2, #120
    beq.n .Lsec21_0000032c
    lsls r5, r5, #4
.Lsec21_00000376:
    adds r1, r2, #0
    subs r1, #48
    lsls r3, r1, #24
    lsrs r3, r3, #24
    cmp r3, #9
    bls.n .Lsec21_00000366
    adds r3, r2, #0
    subs r3, #97
    lsls r3, r3, #24
    lsrs r3, r3, #24
    cmp r3, #5
    bhi.n .Lsec21_00000398
    adds r3, r2, #0
    subs r3, #87
    muls r3, r5
    adds r4, r4, r3
    b.n .Lsec21_0000036c
.Lsec21_00000398:
    adds r3, r2, #0
    subs r3, #65
    lsls r3, r3, #24
    lsrs r3, r3, #24
    cmp r3, #5
    bhi.n .Lsec21_000002ac
    adds r3, r2, #0
    subs r3, #55
    muls r3, r5
    adds r4, r4, r3
    b.n .Lsec21_0000036c
.Lsec21_000003ae:
    adds r0, r4, #0
    ldr r1, [sp, #4]
    ldr r2, [sp, #0]
.Lsec21_000003b4:
    bl _ZN9TiXmlBase18ConvertUTF32ToUTF8EmPcPi
    b.n .Lsec21_0000033a
.Lsec21_000003ba:
    movs r4, #0
    b.n .Lsec21_0000032c
    lsls r0, r0, #0
    .long _ZN9TiXmlBase6entityE
    .long .Lsec49_00000078
    .long .Lsec49_00000004
    .long 0x00000207
.thumb
.thumb_func
_ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, r8
    push {r7}
    adds r4, r0, #0
    adds r5, r1, #0
    adds r6, r2, #0
    mov r8, r3
    cmp r0, #0
    beq.n .Lsec21_00000486
.Lsec21_000003e2:
    cmp r5, #0
    beq.n .Lsec21_00000478
.Lsec21_000003e6:
    cmp r4, #0
    beq.n .Lsec21_00000416
    ldrb r0, [r4, #0]
    cmp r0, #0
    beq.n .Lsec21_00000416
    cmp r6, #0
    bne.n .Lsec21_00000428
    adds r2, r4, #0
.Lsec21_000003f6:
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000412
    cmp r3, r0
    bne.n .Lsec21_00000474
    adds r2, #1
    ldrb r0, [r2, #0]
    adds r5, #1
    cmp r0, #0
    bne.n .Lsec21_000003f6
    ldrb r3, [r5, #0]
    movs r0, #0
    cmp r3, #0
    bne.n .Lsec21_00000422
.Lsec21_00000412:
    movs r0, #1
    b.n .Lsec21_00000422
.Lsec21_00000416:
    ldr r0, [pc, #124]
    ldr r2, [pc, #124]
    ldr r1, [pc, #128]
.Lsec21_0000041c:
    bl __assert
    movs r0, #0
.Lsec21_00000422:
    pop {r2}
    mov r8, r2
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000428:
    adds r7, r4, #0
    b.n .Lsec21_00000444
.Lsec21_0000042c:
    cmp r0, #127
    ble.n .Lsec21_00000466
.Lsec21_00000430:
    adds r0, r4, #0
    cmp r4, #127
    ble.n .Lsec21_00000460
.Lsec21_00000436:
    cmp r0, r6
    bne.n .Lsec21_00000474
    adds r7, #1
    ldrb r0, [r7, #0]
    adds r5, #1
    cmp r0, #0
    beq.n .Lsec21_0000046e
.Lsec21_00000444:
    ldrb r4, [r5, #0]
    cmp r4, #0
    beq.n .Lsec21_00000412
    mov r3, r8
    adds r6, r0, #0
    cmp r3, #1
    beq.n .Lsec21_0000042c
.Lsec21_00000452:
    bl tolower
    adds r6, r0, #0
    adds r0, r4, #0
.Lsec21_0000045a:
    bl tolower
    b.n .Lsec21_00000436
.Lsec21_00000460:
    bl tolower
    b.n .Lsec21_00000436
.Lsec21_00000466:
    bl tolower
    adds r6, r0, #0
    b.n .Lsec21_00000430
.Lsec21_0000046e:
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000412
.Lsec21_00000474:
    movs r0, #0
    b.n .Lsec21_00000422
.Lsec21_00000478:
    movs r1, #135
    ldr r0, [pc, #24]
    ldr r2, [pc, #32]
    lsls r1, r1, #2
.Lsec21_00000480:
    bl __assert
    b.n .Lsec21_000003e6
.Lsec21_00000486:
    ldr r0, [pc, #12]
    ldr r2, [pc, #24]
    ldr r1, [pc, #28]
.Lsec21_0000048c:
    bl __assert
    b.n .Lsec21_000003e2
    lsls r0, r0, #0
    .long .Lsec49_00000004
    .long .Lsec49_000000ac
    .long 0x0000021f
    .long .Lsec49_000000a8
    .long .Lsec49_00000044
    .long 0x0000021b
.thumb
.thumb_func
_ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding:
    push {r4, r5, lr}
    sub sp, #4
    adds r5, r0, #0
    cmp r0, #0
    bne.n .Lsec21_000004bc
.Lsec21_000004b6:
    adds r0, r5, #0
    add sp, #4
    pop {r4, r5, pc}
.Lsec21_000004bc:
    ldrb r4, [r0, #0]
    cmp r4, #0
    beq.n .Lsec21_0000051e
    cmp r1, #1
    beq.n .Lsec21_00000502
.Lsec21_000004c6:
    adds r0, r4, #0
.Lsec21_000004c8:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_000004d8
    cmp r4, #10
    beq.n .Lsec21_000004d8
    cmp r4, #13
    bne.n .Lsec21_000004b6
.Lsec21_000004d8:
    adds r5, #1
    ldrb r4, [r5, #0]
    cmp r4, #0
    bne.n .Lsec21_000004c6
    b.n .Lsec21_000004b6
.Lsec21_000004e2:
    ldrb r3, [r5, #2]
    cmp r3, #191
    beq.n .Lsec21_0000051a
.Lsec21_000004e8:
    adds r0, r4, #0
.Lsec21_000004ea:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_000004fa
    cmp r4, #10
    beq.n .Lsec21_000004fa
    cmp r4, #13
    bne.n .Lsec21_000004b6
.Lsec21_000004fa:
    adds r5, #1
.Lsec21_000004fc:
    ldrb r4, [r5, #0]
    cmp r4, #0
    beq.n .Lsec21_000004b6
.Lsec21_00000502:
    cmp r4, #239
    bne.n .Lsec21_000004e8
    ldrb r3, [r5, #1]
    cmp r3, #187
    beq.n .Lsec21_000004e2
    cmp r3, #191
    bne.n .Lsec21_000004e8
    ldrb r3, [r5, #2]
    cmp r3, #190
    beq.n .Lsec21_0000051a
    cmp r3, #191
    bne.n .Lsec21_000004e8
.Lsec21_0000051a:
    adds r5, #3
    b.n .Lsec21_000004fc
.Lsec21_0000051e:
    movs r5, #0
    b.n .Lsec21_000004b6
    .short 0x0000
.thumb_func
_ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, r8
    push {r7}
    mov r8, r1
    adds r6, r0, #0
    adds r7, r2, #0
    ldr r1, [pc, #116]
    mov r0, r8
    movs r2, #0
.Lsec21_00000536:
    bl _ZN11TiXmlString6assignEPKcj
    cmp r6, #0
    beq.n .Lsec21_0000059a
    ldrb r4, [r6, #0]
    cmp r4, #0
    beq.n .Lsec21_00000596
    adds r0, r4, #0
    adds r1, r7, #0
.Lsec21_00000548:
    bl _ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00000592
.Lsec21_00000550:
    adds r5, r6, #0
    b.n .Lsec21_0000055a
.Lsec21_00000554:
    ldrb r4, [r5, #0]
    cmp r4, #0
    beq.n .Lsec21_0000057c
.Lsec21_0000055a:
    adds r0, r4, #0
    adds r1, r7, #0
.Lsec21_0000055e:
    bl _ZN9TiXmlBase10IsAlphaNumEh13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000576
    cmp r4, #95
    beq.n .Lsec21_00000576
    cmp r4, #45
    beq.n .Lsec21_00000576
    cmp r4, #46
    beq.n .Lsec21_00000576
    cmp r4, #58
    bne.n .Lsec21_0000057c
.Lsec21_00000576:
    adds r5, #1
    cmp r5, #0
    bne.n .Lsec21_00000554
.Lsec21_0000057c:
    subs r2, r5, r6
    cmp r2, #0
    ble.n .Lsec21_0000058a
    mov r0, r8
    adds r1, r6, #0
.Lsec21_00000586:
    bl _ZN11TiXmlString6assignEPKcj
.Lsec21_0000058a:
    adds r0, r5, #0
    pop {r2}
    mov r8, r2
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000592:
    cmp r4, #95
    beq.n .Lsec21_00000550
.Lsec21_00000596:
    movs r5, #0
    b.n .Lsec21_0000058a
.Lsec21_0000059a:
    ldr r0, [pc, #16]
    ldr r2, [pc, #16]
    ldr r1, [pc, #20]
.Lsec21_000005a0:
    bl __assert
    movs r5, #0
    b.n .Lsec21_0000058a
    .long .Lsec49_00000000
    .long .Lsec49_00000004
    .long .Lsec49_00000044
    .long 0x00000197
.thumb
.thumb_func
_ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, sl
    mov r6, r8
    push {r6, r7}
    sub sp, #4
    adds r7, r3, #0
    add r3, sp, #32
    ldrb r3, [r3, #0]
    movs r5, #44
    mov sl, r3
    ldrb r3, [r0, r5]
    adds r6, r0, #0
    adds r4, r1, #0
    mov r8, r2
    cmp r3, #0
    bne.n .Lsec21_00000622
    subs r3, r1, #1
    cmp r3, #15
    bhi.n .Lsec21_0000062c
.Lsec21_000005de:
    ldr r2, [pc, #92]
    movs r3, #1
    strb r3, [r6, r5]
    lsls r3, r4, #2
    str r4, [r6, #48]
    ldr r4, [r3, r2]
    adds r5, r6, #0
    adds r0, r4, #0
.Lsec21_000005ee:
    bl strlen
    adds r5, #52
    adds r2, r0, #0
    adds r1, r4, #0
    adds r0, r5, #0
.Lsec21_000005fa:
    bl _ZN11TiXmlString6assignEPKcj
    adds r4, r6, #0
    movs r3, #1
    negs r3, r3
    adds r4, #60
    mov r0, r8
    str r3, [r4, #4]
    str r3, [r6, #60]
    cmp r0, #0
    beq.n .Lsec21_00000622
    cmp r7, #0
    beq.n .Lsec21_00000622
    adds r0, r7, #0
    mov r1, r8
    mov r2, sl
.Lsec21_0000061a:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    ldmia r7!, {r0, r1}
    stmia r4!, {r0, r1}
.Lsec21_00000622:
    add sp, #4
    pop {r2, r3}
    mov r8, r2
    mov sl, r3
    pop {r4, r5, r6, r7, pc}
.Lsec21_0000062c:
    movs r1, #201
    ldr r0, [pc, #16]
    ldr r2, [pc, #16]
    lsls r1, r1, #2
.Lsec21_00000634:
    bl __assert
    b.n .Lsec21_000005de
    lsls r0, r0, #0
    .long _ZN9TiXmlBase11errorStringE
    .long .Lsec49_00000004
    .long .Lsec49_000000b0
.thumb
.thumb_func
_ZN12TiXmlComment5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    sub sp, #12
    adds r7, r3, #0
    adds r4, r1, #0
    mov sl, r2
    mov r8, r0
.Lsec21_0000065e:
    bl _ZNK9TiXmlNode11GetDocumentEv
    mov fp, r0
    ldr r0, [pc, #168]
    mov r6, r8
    mov r9, r0
    adds r6, #32
    mov r1, r9
    movs r2, #0
    adds r0, r6, #0
.Lsec21_00000672:
    bl _ZN11TiXmlString6assignEPKcj
    adds r1, r7, #0
    adds r0, r4, #0
.Lsec21_0000067a:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    mov r1, sl
    adds r5, r0, #0
    cmp r1, #0
    beq.n .Lsec21_0000069a
    mov r0, sl
    adds r1, r5, #0
    adds r2, r7, #0
.Lsec21_0000068c:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    mov r3, r8
    adds r3, #4
    mov r2, sl
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
.Lsec21_0000069a:
    ldr r1, [pc, #120]
    adds r0, r5, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_000006a2:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_000006fc
    adds r4, r5, #4
    adds r0, r6, #0
    mov r1, r9
    movs r2, #0
.Lsec21_000006b2:
    bl _ZN11TiXmlString6assignEPKcj
    cmp r4, #0
    beq.n .Lsec21_000006ec
    ldrb r3, [r5, #4]
    cmp r3, #0
    beq.n .Lsec21_000006ea
    ldr r5, [pc, #84]
    b.n .Lsec21_000006da
.Lsec21_000006c4:
    adds r1, r4, #0
    adds r0, r6, #0
    movs r2, #1
    adds r4, #1
.Lsec21_000006cc:
    bl _ZN11TiXmlString6appendEPKcj
    cmp r4, #0
    beq.n .Lsec21_000006ec
    ldrb r3, [r4, #0]
    cmp r3, #0
    beq.n .Lsec21_000006ea
.Lsec21_000006da:
    adds r0, r4, #0
    adds r1, r5, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_000006e2:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_000006c4
.Lsec21_000006ea:
    adds r4, #3
.Lsec21_000006ec:
    adds r0, r4, #0
    add sp, #12
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_000006fc:
    mov r0, fp
    movs r1, #11
    adds r2, r5, #0
    mov r3, sl
    str r7, [sp, #0]
.Lsec21_00000706:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r4, #0
    b.n .Lsec21_000006ec
    lsls r0, r0, #0
    .long .Lsec49_00000000
    .long .Lsec49_000000dc
    .long .Lsec49_000000e4
.thumb
.thumb_func
_ZN12TiXmlUnknown5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, r8
    push {r7}
    sub sp, #16
    adds r4, r1, #0
    adds r7, r3, #0
    adds r5, r2, #0
    adds r6, r0, #0
.Lsec21_0000072c:
    bl _ZNK9TiXmlNode11GetDocumentEv
    adds r1, r7, #0
    mov r8, r0
    adds r0, r4, #0
.Lsec21_00000736:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    cmp r5, #0
    beq.n .Lsec21_00000752
    adds r0, r5, #0
    adds r1, r4, #0
    adds r2, r7, #0
.Lsec21_00000746:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    adds r3, r6, #4
    adds r2, r5, #0
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
.Lsec21_00000752:
    cmp r4, #0
    beq.n .Lsec21_0000075c
    ldrb r3, [r4, #0]
    cmp r3, #0
    bne.n .Lsec21_0000076e
.Lsec21_0000075c:
    mov r3, r8
    cmp r3, #0
    bne.n .Lsec21_000007cc
.Lsec21_00000762:
    movs r5, #0
.Lsec21_00000764:
    adds r0, r5, #0
    add sp, #16
    pop {r2}
    mov r8, r2
    pop {r4, r5, r6, r7, pc}
.Lsec21_0000076e:
    cmp r3, #60
    bne.n .Lsec21_0000075c
    adds r6, #32
    adds r5, r4, #1
    ldr r1, [pc, #100]
    adds r0, r6, #0
    movs r2, #0
.Lsec21_0000077c:
    bl _ZN11TiXmlString6assignEPKcj
    cmp r5, #0
    beq.n .Lsec21_000007b0
    ldrb r0, [r4, #1]
    cmp r0, #0
    beq.n .Lsec21_00000764
    cmp r0, #62
    beq.n .Lsec21_000007c8
    mov r4, sp
    adds r4, #15
    b.n .Lsec21_0000079e
.Lsec21_00000794:
    ldrb r0, [r5, #0]
    cmp r0, #0
    beq.n .Lsec21_00000764
    cmp r0, #62
    beq.n .Lsec21_000007c8
.Lsec21_0000079e:
    strb r0, [r4, #0]
    adds r1, r4, #0
    adds r0, r6, #0
    movs r2, #1
    adds r5, #1
.Lsec21_000007a8:
    bl _ZN11TiXmlString6appendEPKcj
    cmp r5, #0
    bne.n .Lsec21_00000794
.Lsec21_000007b0:
    mov r0, r8
    cmp r0, #0
    beq.n .Lsec21_000007c2
    movs r1, #10
    movs r2, #0
    movs r3, #0
    str r7, [sp, #0]
.Lsec21_000007be:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
.Lsec21_000007c2:
    ldrb r3, [r5, #0]
    cmp r3, #62
    bne.n .Lsec21_00000764
.Lsec21_000007c8:
    adds r5, #1
    b.n .Lsec21_00000764
.Lsec21_000007cc:
    mov r0, r8
    movs r1, #10
    adds r2, r4, #0
    adds r3, r5, #0
    str r7, [sp, #0]
.Lsec21_000007d6:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    b.n .Lsec21_00000762
    .long .Lsec49_00000000
.thumb
.thumb_func
_ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    sub sp, #12
    adds r6, r0, #0
    adds r0, r1, #0
    adds r1, r2, #0
    adds r5, r2, #0
.Lsec21_000007ec:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    bne.n .Lsec21_000007fc
.Lsec21_000007f6:
    movs r0, #0
.Lsec21_000007f8:
    add sp, #12
    pop {r4, r5, r6, r7, pc}
.Lsec21_000007fc:
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_000007f6
    cmp r3, #60
    bne.n .Lsec21_000007f6
    adds r0, r6, #0
.Lsec21_00000808:
    bl _ZNK9TiXmlNode11GetDocumentEv
    adds r1, r5, #0
    adds r7, r0, #0
    adds r0, r4, #0
.Lsec21_00000812:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    beq.n .Lsec21_000007f6
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_000007f6
    ldr r1, [pc, #248]
    movs r2, #1
    adds r3, r5, #0
.Lsec21_00000828:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00000850
    movs r0, #56
.Lsec21_00000832:
    bl _Znwj
    movs r1, #5
    adds r4, r0, #0
.Lsec21_0000083a:
    bl _ZN9TiXmlNodeC2ENS_8NodeTypeE
    ldr r3, [pc, #224]
    adds r0, r4, #0
    str r3, [r4, #0]
    ldr r3, [pc, #220]
    str r6, [r0, #16]
    str r3, [r4, #44]
    str r3, [r4, #48]
    str r3, [r4, #52]
    b.n .Lsec21_000007f8
.Lsec21_00000850:
    ldr r1, [pc, #212]
    adds r0, r4, #0
    movs r2, #0
    adds r3, r5, #0
.Lsec21_00000858:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00000878
    movs r0, #44
.Lsec21_00000862:
    bl _Znwj
    movs r1, #2
    adds r4, r0, #0
.Lsec21_0000086a:
    bl _ZN9TiXmlNodeC2ENS_8NodeTypeE
    ldr r3, [pc, #188]
    adds r0, r4, #0
    str r3, [r4, #0]
    str r6, [r0, #16]
    b.n .Lsec21_000007f8
.Lsec21_00000878:
    ldr r1, [pc, #180]
    adds r0, r4, #0
    movs r2, #0
    adds r3, r5, #0
.Lsec21_00000880:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_000008b2
    movs r0, #48
.Lsec21_0000088a:
    bl _Znwj
    movs r1, #4
    adds r4, r0, #0
.Lsec21_00000892:
    bl _ZN9TiXmlNodeC2ENS_8NodeTypeE
    ldr r3, [pc, #156]
    adds r0, r4, #0
    str r3, [r4, #0]
    movs r2, #0
    adds r0, #32
    ldr r1, [pc, #148]
.Lsec21_000008a2:
    bl _ZN11TiXmlString6assignEPKcj
    movs r2, #1
    movs r3, #44
    adds r0, r4, #0
    strb r2, [r4, r3]
    str r6, [r0, #16]
    b.n .Lsec21_000007f8
.Lsec21_000008b2:
    ldr r1, [pc, #136]
    adds r0, r4, #0
    movs r2, #0
    adds r3, r5, #0
.Lsec21_000008ba:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_000008ec
    ldrb r4, [r4, #1]
    adds r1, r5, #0
    adds r0, r4, #0
.Lsec21_000008c8:
    bl _ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_000008d4
    cmp r4, #95
    bne.n .Lsec21_000008ec
.Lsec21_000008d4:
    movs r0, #80
.Lsec21_000008d6:
    bl _Znwj
    ldr r1, [pc, #92]
    adds r4, r0, #0
.Lsec21_000008de:
    bl _ZN12TiXmlElementC1EPKc
    cmp r4, #0
    beq.n .Lsec21_00000904
    adds r0, r4, #0
    str r6, [r0, #16]
    b.n .Lsec21_000007f8
.Lsec21_000008ec:
    movs r0, #44
.Lsec21_000008ee:
    bl _Znwj
    movs r1, #3
    adds r4, r0, #0
.Lsec21_000008f6:
    bl _ZN9TiXmlNodeC2ENS_8NodeTypeE
    ldr r3, [pc, #68]
    adds r0, r4, #0
    str r3, [r4, #0]
    str r6, [r0, #16]
    b.n .Lsec21_000007f8
.Lsec21_00000904:
    cmp r7, #0
    bne.n .Lsec21_0000090a
    b.n .Lsec21_000007f6
.Lsec21_0000090a:
    adds r0, r7, #0
    movs r1, #3
    movs r2, #0
    movs r3, #0
    str r4, [sp, #0]
.Lsec21_00000914:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r0, #0
    b.n .Lsec21_000007f8
    .long .Lsec49_000000e8
    .long _ZTV16TiXmlDeclaration + 0x8
    .long _ZN11TiXmlString8nullrep_E
    .long .Lsec49_000000dc
    .long _ZTV12TiXmlComment + 0x8
    .long .Lsec49_000000f0
    .long _ZTV9TiXmlText + 0x8
    .long .Lsec49_00000000
    .long .Lsec49_000000fc
    .long _ZTV12TiXmlUnknown + 0x8
.thumb
.thumb_func
_ZN12TiXmlElement9ReadValueEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    sub sp, #12
    adds r4, r1, #0
    adds r7, r3, #0
    mov sl, r2
    mov r9, r0
.Lsec21_0000095a:
    bl _ZNK9TiXmlNode11GetDocumentEv
    adds r1, r7, #0
    mov fp, r0
    adds r0, r4, #0
.Lsec21_00000964:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000a10
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00000a18
    mov r8, r4
    b.n .Lsec21_000009b0
.Lsec21_00000978:
    ldr r3, [r5, #0]
    adds r0, r5, #0
    ldr r4, [r3, #12]
    adds r1, r6, #0
    mov r2, sl
    adds r3, r7, #0
    blx r4
    adds r4, r0, #0
    adds r0, r5, #0
.Lsec21_0000098a:
    bl _ZNK9TiXmlText5BlankEv
    cmp r0, #0
    beq.n .Lsec21_000009fa
.Lsec21_00000992:
    ldr r3, [r5, #0]
    adds r0, r5, #0
    ldr r3, [r3, #4]
    blx r3
    adds r0, r4, #0
    adds r1, r7, #0
.Lsec21_0000099e:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000a10
.Lsec21_000009a8:
    ldrb r3, [r0, #0]
    mov r8, r4
    cmp r3, #0
    beq.n .Lsec21_00000a18
.Lsec21_000009b0:
    cmp r3, #60
    beq.n .Lsec21_00000a28
    movs r0, #48
.Lsec21_000009b6:
    bl _Znwj
    movs r1, #4
    adds r5, r0, #0
.Lsec21_000009be:
    bl _ZN9TiXmlNodeC2ENS_8NodeTypeE
    ldr r3, [pc, #176]
    adds r0, r5, #0
    str r3, [r5, #0]
    movs r2, #0
    adds r0, #32
    ldr r1, [pc, #168]
.Lsec21_000009ce:
    bl _ZN11TiXmlString6assignEPKcj
    movs r3, #44
    movs r2, #0
    strb r2, [r5, r3]
    ldr r3, [pc, #160]
    ldrb r3, [r3, #0]
    cmp r3, #0
    bne.n .Lsec21_00000978
    ldr r3, [r5, #0]
    adds r0, r5, #0
    ldr r4, [r3, #12]
    mov r1, r8
    mov r2, sl
    adds r3, r7, #0
    blx r4
    adds r4, r0, #0
    adds r0, r5, #0
.Lsec21_000009f2:
    bl _ZNK9TiXmlText5BlankEv
    cmp r0, #0
    bne.n .Lsec21_00000992
.Lsec21_000009fa:
    mov r0, r9
    adds r1, r5, #0
.Lsec21_000009fe:
    bl _ZN9TiXmlNode12LinkEndChildEPS_
.Lsec21_00000a02:
    adds r0, r4, #0
    adds r1, r7, #0
.Lsec21_00000a06:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    bne.n .Lsec21_000009a8
.Lsec21_00000a10:
    mov r3, fp
    cmp r3, #0
    bne.n .Lsec21_00000a60
.Lsec21_00000a16:
    movs r6, #0
.Lsec21_00000a18:
    adds r0, r6, #0
    add sp, #12
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000a28:
    ldr r1, [pc, #84]
    adds r0, r6, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_00000a30:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000a18
    mov r0, r9
    adds r1, r6, #0
    adds r2, r7, #0
.Lsec21_00000a3e:
    bl _ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding
    adds r5, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000a16
    ldr r3, [r0, #0]
    adds r1, r6, #0
    ldr r4, [r3, #12]
    mov r2, sl
    adds r3, r7, #0
    blx r4
    adds r1, r5, #0
    adds r4, r0, #0
    mov r0, r9
.Lsec21_00000a5a:
    bl _ZN9TiXmlNode12LinkEndChildEPS_
    b.n .Lsec21_00000a02
.Lsec21_00000a60:
    mov r0, fp
    movs r1, #6
    movs r2, #0
    movs r3, #0
    str r7, [sp, #0]
.Lsec21_00000a6a:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r6, #0
    b.n .Lsec21_00000a18
    lsls r0, r0, #0
    .long _ZTV9TiXmlText + 0x8
    .long .Lsec49_00000000
    .long _ZN9TiXmlBase18condenseWhiteSpaceE
    .long .Lsec49_00000100
.thumb
.thumb_func
_ZN12TiXmlElement5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    sub sp, #28
    mov fp, r0
    adds r0, r1, #0
    adds r1, r3, #0
    mov r9, r2
    adds r7, r3, #0
.Lsec21_00000a9c:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    mov r0, fp
.Lsec21_00000aa4:
    bl _ZNK9TiXmlNode11GetDocumentEv
    mov r8, r0
    cmp r4, #0
    beq.n .Lsec21_00000b10
    ldrb r3, [r4, #0]
    cmp r3, #0
    beq.n .Lsec21_00000b10
    mov r2, r9
    cmp r2, #0
    beq.n .Lsec21_00000ad0
    mov r0, r9
    adds r1, r4, #0
    adds r2, r7, #0
.Lsec21_00000ac0:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    mov r3, fp
    adds r3, #4
    mov r2, r9
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
    ldrb r3, [r4, #0]
.Lsec21_00000ad0:
    cmp r3, #60
    bne.n .Lsec21_00000b28
    adds r0, r4, #1
    adds r1, r7, #0
.Lsec21_00000ad8:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    mov r1, fp
    adds r1, #32
    adds r2, r7, #0
    adds r4, r0, #0
.Lsec21_00000ae4:
    bl _ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding
    mov sl, r0
    cmp r0, #0
    beq.n .Lsec21_00000af4
    ldrb r3, [r0, #0]
    cmp r3, #0
    bne.n .Lsec21_00000b42
.Lsec21_00000af4:
    mov r0, r8
    cmp r0, #0
    beq.n .Lsec21_00000afc
    b.n .Lsec21_00000c60
.Lsec21_00000afc:
    movs r2, #0
    mov sl, r2
.Lsec21_00000b00:
    mov r0, sl
    add sp, #28
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000b10:
    mov r0, r8
    cmp r0, #0
    beq.n .Lsec21_00000afc
    movs r1, #4
    movs r2, #0
    movs r3, #0
    str r7, [sp, #0]
.Lsec21_00000b1e:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r1, #0
    mov sl, r1
    b.n .Lsec21_00000b00
.Lsec21_00000b28:
    mov r2, r8
    cmp r2, #0
    beq.n .Lsec21_00000afc
    mov r3, r9
    mov r0, r8
    movs r1, #4
    adds r2, r4, #0
    str r7, [sp, #0]
.Lsec21_00000b38:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r3, #0
    mov sl, r3
    b.n .Lsec21_00000b00
.Lsec21_00000b42:
    movs r0, #0
    str r0, [sp, #20]
    movs r0, #16
.Lsec21_00000b48:
    bl _Znaj
    movs r3, #0
    str r0, [sp, #20]
    strb r3, [r0, #10]
    ldr r3, [sp, #20]
    movs r2, #2
    str r2, [r0, #0]
    adds r0, r3, #0
    str r2, [r3, #4]
    ldr r1, [pc, #440]
    ldr r2, [r3, #0]
    adds r0, #8
.Lsec21_00000b62:
    bl memcpy
    mov r2, fp
    ldr r3, [r2, #32]
    add r4, sp, #20
    adds r1, r3, #0
    ldr r2, [r3, #0]
    adds r1, #8
    adds r0, r4, #0
.Lsec21_00000b74:
    bl _ZN11TiXmlString6appendEPKcj
    ldr r1, [pc, #416]
    adds r0, r4, #0
    movs r2, #1
.Lsec21_00000b7e:
    bl _ZN11TiXmlString6appendEPKcj
    mov r0, sl
    ldrb r3, [r0, #0]
    cmp r3, #0
    bne.n .Lsec21_00000b8c
    b.n .Lsec21_00000d0e
.Lsec21_00000b8c:
    ldr r1, [pc, #400]
    str r1, [sp, #12]
    b.n .Lsec21_00000c00
.Lsec21_00000b92:
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00000c0e
    cmp r3, #47
    beq.n .Lsec21_00000c72
    cmp r3, #62
    beq.n .Lsec21_00000c90
    movs r0, #36
.Lsec21_00000ba2:
    bl _Znwj
    movs r3, #1
    ldr r2, [pc, #376]
    negs r3, r3
    str r3, [r0, #8]
    str r3, [r0, #4]
    movs r3, #0
    adds r6, r0, #0
    str r3, [r0, #12]
    str r2, [r0, #0]
    ldr r0, [sp, #12]
    mov r1, r8
    str r0, [r6, #20]
    str r0, [r6, #24]
    str r3, [r6, #32]
    str r3, [r6, #28]
    str r1, [r6, #16]
    ldr r4, [r2, #12]
    adds r0, r6, #0
    adds r1, r5, #0
    mov r2, r9
    adds r3, r7, #0
    blx r4
    mov sl, r0
    cmp r0, #0
    beq.n .Lsec21_00000c2a
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00000c2a
    mov r4, fp
    ldr r1, [r6, #20]
    adds r4, #44
    adds r1, #8
    adds r0, r4, #0
.Lsec21_00000be8:
    bl _ZNK17TiXmlAttributeSet4FindEPKc
    cmp r0, #0
    bne.n .Lsec21_00000cb8
    adds r0, r4, #0
    adds r1, r6, #0
.Lsec21_00000bf4:
    bl _ZN17TiXmlAttributeSet3AddEP14TiXmlAttribute
    mov r0, sl
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00000c4a
.Lsec21_00000c00:
    mov r0, sl
    adds r1, r7, #0
.Lsec21_00000c04:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r5, r0, #0
    cmp r0, #0
    bne.n .Lsec21_00000b92
.Lsec21_00000c0e:
    mov r2, r8
    cmp r2, #0
    beq.n .Lsec21_00000c8a
    str r7, [sp, #0]
    mov r0, r8
    movs r1, #7
    mov r2, sl
.Lsec21_00000c1c:
    mov r3, r9
.Lsec21_00000c1e:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r3, #0
    ldr r0, [sp, #20]
    mov sl, r3
    b.n .Lsec21_00000c4c
.Lsec21_00000c2a:
    mov r2, r8
    cmp r2, #0
    beq.n .Lsec21_00000c3e
    mov r0, r8
    movs r1, #4
    adds r2, r5, #0
    mov r3, r9
    str r7, [sp, #0]
.Lsec21_00000c3a:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
.Lsec21_00000c3e:
    ldr r3, [r6, #0]
    adds r0, r6, #0
    ldr r3, [r3, #4]
    blx r3
    movs r3, #0
    mov sl, r3
.Lsec21_00000c4a:
    ldr r0, [sp, #20]
.Lsec21_00000c4c:
    ldr r1, [sp, #12]
    cmp r0, r1
    bne.n .Lsec21_00000c54
    b.n .Lsec21_00000b00
.Lsec21_00000c54:
    cmp r0, #0
    bne.n .Lsec21_00000c5a
    b.n .Lsec21_00000b00
.Lsec21_00000c5a:
    bl _ZdaPv
    b.n .Lsec21_00000b00
.Lsec21_00000c60:
    movs r1, #5
    adds r2, r4, #0
    mov r3, r9
    str r7, [sp, #0]
.Lsec21_00000c68:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r1, #0
    mov sl, r1
    b.n .Lsec21_00000b00
.Lsec21_00000c72:
    ldrb r3, [r0, #1]
    adds r2, r0, #1
    cmp r3, #62
    beq.n .Lsec21_00000cde
    mov r0, r8
    cmp r0, #0
    beq.n .Lsec21_00000c8a
    str r7, [sp, #0]
    movs r1, #8
.Lsec21_00000c84:
    mov r3, r9
.Lsec21_00000c86:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
.Lsec21_00000c8a:
    movs r1, #0
    mov sl, r1
    b.n .Lsec21_00000c4a
.Lsec21_00000c90:
    adds r1, r0, #1
    mov r2, r9
    mov r0, fp
    adds r3, r7, #0
.Lsec21_00000c98:
    bl _ZN12TiXmlElement9ReadValueEPKcP16TiXmlParsingData13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000ca8
    ldrb r3, [r0, #0]
    cmp r3, #0
    bne.n .Lsec21_00000ce6
.Lsec21_00000ca8:
    mov r2, r8
    cmp r2, #0
    beq.n .Lsec21_00000c8a
    mov r0, r8
    movs r1, #9
    adds r2, r4, #0
    str r7, [sp, #0]
    b.n .Lsec21_00000c1c
.Lsec21_00000cb8:
    ldr r4, [r6, #24]
    adds r5, r0, #0
    adds r4, #8
    adds r0, r4, #0
.Lsec21_00000cc0:
    bl strlen
    adds r5, #24
    adds r2, r0, #0
    adds r1, r4, #0
    adds r0, r5, #0
.Lsec21_00000ccc:
    bl _ZN11TiXmlString6assignEPKcj
    ldr r3, [r6, #0]
    adds r0, r6, #0
    ldr r3, [r3, #4]
    blx r3
    movs r2, #0
    mov sl, r2
    b.n .Lsec21_00000c4a
.Lsec21_00000cde:
    adds r2, #1
    ldr r0, [sp, #20]
    mov sl, r2
    b.n .Lsec21_00000c4c
.Lsec21_00000ce6:
    ldr r1, [sp, #20]
    movs r2, #0
    adds r1, #8
    adds r3, r7, #0
.Lsec21_00000cee:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000d04
    mov r0, r8
    cmp r0, #0
    beq.n .Lsec21_00000c8a
    movs r1, #9
    adds r2, r4, #0
    str r7, [sp, #0]
    b.n .Lsec21_00000c84
.Lsec21_00000d04:
    ldr r0, [sp, #20]
    ldr r3, [r0, #0]
    adds r4, r4, r3
    mov sl, r4
    b.n .Lsec21_00000c4c
.Lsec21_00000d0e:
    ldr r3, [pc, #16]
    ldr r0, [sp, #20]
    str r3, [sp, #12]
    b.n .Lsec21_00000c4c
    lsls r0, r0, #0
    .long .Lsec49_00000100
    .long .Lsec49_00000104
    .long _ZN11TiXmlString8nullrep_E
    .long _ZTV14TiXmlAttribute + 0x8
.thumb
.thumb_func
_ZN13TiXmlDocument5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, sl
    mov r6, r8
    push {r6, r7}
    movs r4, #0
    mov r8, r3
    movs r3, #44
    adds r7, r0, #0
    strb r4, [r0, r3]
    str r4, [r0, #48]
    sub sp, #28
    adds r5, r1, #0
    adds r6, r2, #0
    adds r0, #52
    ldr r1, [pc, #356]
    movs r2, #0
.Lsec21_00000d48:
    bl _ZN11TiXmlString6assignEPKcj
    str r4, [r7, #64]
    str r4, [r7, #60]
    cmp r5, #0
    beq.n .Lsec21_00000e28
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000e28
    movs r3, #1
    negs r3, r3
    adds r0, r7, #4
    str r3, [r0, #4]
    str r3, [r7, #4]
    cmp r6, #0
    bne.n .Lsec21_00000d6a
    b.n .Lsec21_00000e88
.Lsec21_00000d6a:
    ldr r3, [r6, #0]
    str r3, [r7, #4]
    ldr r3, [r6, #4]
    str r3, [r7, #8]
.Lsec21_00000d72:
    ldr r3, [r7, #56]
    ldr r1, [r7, #8]
    ldr r2, [r7, #4]
    add r4, sp, #8
    str r3, [sp, #20]
    str r1, [sp, #12]
    str r5, [sp, #16]
    str r2, [sp, #8]
    adds r3, r4, #0
    mov sl, r4
    ldmia r3!, {r1, r4}
    stmia r0!, {r1, r4}
    mov r1, r8
    cmp r1, #0
    bne.n .Lsec21_00000d96
    ldrb r3, [r5, #0]
    cmp r3, #239
    beq.n .Lsec21_00000e44
.Lsec21_00000d96:
    adds r0, r5, #0
    mov r1, r8
.Lsec21_00000d9a:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    bne.n .Lsec21_00000db4
    b.n .Lsec21_00000e9a
.Lsec21_00000da6:
    adds r0, r6, #0
    mov r1, r8
.Lsec21_00000daa:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000e1c
.Lsec21_00000db4:
    ldrb r3, [r6, #0]
    cmp r3, #0
    beq.n .Lsec21_00000e1c
    adds r0, r7, #0
    adds r1, r6, #0
    mov r2, r8
.Lsec21_00000dc0:
    bl _ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding
    adds r5, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000e1c
    ldr r3, [r0, #0]
    adds r1, r6, #0
    ldr r4, [r3, #12]
    mov r2, sl
    mov r3, r8
    blx r4
    adds r1, r5, #0
    adds r6, r0, #0
    adds r0, r7, #0
.Lsec21_00000ddc:
    bl _ZN9TiXmlNode12LinkEndChildEPS_
    mov r3, r8
    cmp r3, #0
    bne.n .Lsec21_00000da6
    ldr r3, [r5, #0]
    adds r0, r5, #0
    ldr r3, [r3, #60]
    blx r3
    cmp r0, #0
    beq.n .Lsec21_00000da6
    ldr r3, [r5, #0]
    adds r0, r5, #0
    ldr r3, [r3, #60]
    blx r3
    ldr r4, [r0, #48]
    adds r5, r4, #0
    adds r5, #8
    cmp r5, #0
    beq.n .Lsec21_00000e8e
.Lsec21_00000e04:
    ldrb r3, [r4, #8]
    cmp r3, #0
    bne.n .Lsec21_00000e62
.Lsec21_00000e0a:
    movs r1, #1
    mov r8, r1
    adds r0, r6, #0
    mov r1, r8
.Lsec21_00000e12:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r6, r0, #0
    cmp r0, #0
    bne.n .Lsec21_00000db4
.Lsec21_00000e1c:
    ldr r3, [r7, #24]
    cmp r3, #0
    bne.n .Lsec21_00000e38
    mov r3, r8
    str r3, [sp, #0]
    b.n .Lsec21_00000e2a
.Lsec21_00000e28:
    str r4, [sp, #0]
.Lsec21_00000e2a:
    adds r0, r7, #0
    movs r1, #13
    movs r2, #0
    movs r3, #0
.Lsec21_00000e32:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r6, #0
.Lsec21_00000e38:
    adds r0, r6, #0
    add sp, #28
    pop {r2, r3}
    mov r8, r2
    mov sl, r3
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000e44:
    ldrb r3, [r5, #1]
    cmp r3, #0
    beq.n .Lsec21_00000d96
    cmp r3, #187
    bne.n .Lsec21_00000d96
    ldrb r3, [r5, #2]
    cmp r3, #0
    beq.n .Lsec21_00000d96
    cmp r3, #191
    bne.n .Lsec21_00000d96
    movs r2, #1
    movs r3, #68
    mov r8, r2
    strb r2, [r7, r3]
    b.n .Lsec21_00000d96
.Lsec21_00000e62:
    ldr r1, [pc, #76]
    adds r0, r5, #0
    movs r2, #1
    movs r3, #0
.Lsec21_00000e6a:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000e0a
    ldr r1, [pc, #64]
    adds r0, r5, #0
    movs r2, #1
    movs r3, #0
.Lsec21_00000e7a:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000e0a
    movs r4, #2
    mov r8, r4
    b.n .Lsec21_00000da6
.Lsec21_00000e88:
    str r6, [r7, #4]
    str r6, [r7, #8]
    b.n .Lsec21_00000d72
.Lsec21_00000e8e:
    ldr r0, [pc, #40]
    ldr r2, [pc, #40]
    ldr r1, [pc, #44]
.Lsec21_00000e94:
    bl __assert
    b.n .Lsec21_00000e04
.Lsec21_00000e9a:
    str r0, [sp, #0]
    movs r1, #13
    adds r0, r7, #0
    movs r2, #0
    movs r3, #0
.Lsec21_00000ea4:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    b.n .Lsec21_00000e38
    lsls r0, r0, #0
    .long .Lsec49_00000000
    .long .Lsec49_0000010c
    .long .Lsec49_00000114
    .long .Lsec49_00000004
    .long .Lsec49_00000108
    .long 0x00000305
.thumb
.thumb_func
_ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, sl
    mov r6, r9
    mov r5, r8
    push {r5, r6, r7}
    sub sp, #16
    mov r8, r3
    add r3, sp, #48
    ldrb r3, [r3, #0]
    mov sl, r1
    adds r4, r2, #0
    adds r5, r0, #0
    mov r9, r3
    ldr r1, [pc, #488]
    add r3, sp, #52
    mov r0, sl
    movs r2, #0
    ldrb r6, [r3, #0]
.Lsec21_00000ee8:
    bl _ZN11TiXmlString6assignEPKcj
    cmp r4, #0
    beq.n .Lsec21_00000ef8
    ldr r3, [pc, #472]
    ldrb r3, [r3, #0]
    cmp r3, #0
    bne.n .Lsec21_00000fcc
.Lsec21_00000ef8:
    cmp r5, #0
    beq.n .Lsec21_00000f92
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000f86
    add r4, sp, #4
    b.n .Lsec21_00000f28
.Lsec21_00000f06:
    movs r2, #1
    str r2, [sp, #12]
.Lsec21_00000f0a:
    ldrb r3, [r5, #0]
    cmp r3, #38
    beq.n .Lsec21_00000fa0
    ldr r2, [sp, #12]
    strb r3, [r4, #0]
    adds r5, #1
.Lsec21_00000f16:
    mov r0, sl
    adds r1, r4, #0
.Lsec21_00000f1a:
    bl _ZN11TiXmlString6appendEPKcj
    cmp r5, #0
    beq.n .Lsec21_00000f92
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000f86
.Lsec21_00000f28:
    adds r0, r5, #0
    mov r1, r8
    mov r2, r9
    adds r3, r6, #0
.Lsec21_00000f30:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000f86
    ldr r1, [pc, #404]
    adds r0, r4, #0
    movs r2, #4
.Lsec21_00000f3e:
    bl memcpy
    cmp r6, #1
    bne.n .Lsec21_00000f06
    ldrb r3, [r5, #0]
    ldr r2, [pc, #392]
    lsls r3, r3, #2
    ldr r2, [r3, r2]
    str r2, [sp, #12]
    cmp r2, #4
    bhi.n .Lsec21_00000fbe
.Lsec21_00000f54:
    ldr r2, [sp, #12]
    adds r7, r2, #0
    cmp r2, #1
    beq.n .Lsec21_00000f0a
    cmp r2, #0
    beq.n .Lsec21_00000fb2
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000f82
    cmp r2, #0
    ble.n .Lsec21_00000f82
    movs r1, #0
    movs r0, #0
    b.n .Lsec21_00000f74
.Lsec21_00000f70:
    cmp r2, r1
    beq.n .Lsec21_00000f80
.Lsec21_00000f74:
    strb r3, [r4, r0]
    adds r1, #1
    ldrb r3, [r1, r5]
    adds r0, r1, #0
    cmp r3, #0
    bne.n .Lsec21_00000f70
.Lsec21_00000f80:
    ldr r2, [sp, #12]
.Lsec21_00000f82:
    adds r5, r5, r7
    b.n .Lsec21_00000f16
.Lsec21_00000f86:
    cmp r5, #0
    beq.n .Lsec21_00000f92
    mov r0, r8
.Lsec21_00000f8c:
    bl strlen
    adds r5, r5, r0
.Lsec21_00000f92:
    adds r0, r5, #0
    add sp, #16
    pop {r2, r3, r4}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    pop {r4, r5, r6, r7, pc}
.Lsec21_00000fa0:
    adds r0, r5, #0
    add r2, sp, #12
    adds r1, r4, #0
    adds r3, r6, #0
.Lsec21_00000fa8:
    bl _ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding
    ldr r2, [sp, #12]
    adds r5, r0, #0
    b.n .Lsec21_00000f16
.Lsec21_00000fb2:
    mov r0, sl
    adds r1, r4, #0
.Lsec21_00000fb6:
    bl _ZN11TiXmlString6appendEPKcj
    movs r5, #0
    b.n .Lsec21_00000f92
.Lsec21_00000fbe:
    movs r1, #167
    ldr r0, [pc, #276]
    ldr r2, [pc, #280]
    lsls r1, r1, #1
.Lsec21_00000fc6:
    bl __assert
    b.n .Lsec21_00000f54
.Lsec21_00000fcc:
    adds r0, r5, #0
    adds r1, r6, #0
.Lsec21_00000fd0:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r5, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00000f92
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00000f86
    movs r4, #0
    b.n .Lsec21_00001028
.Lsec21_00000fe4:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_00001042
    cmp r4, #0
    bne.n .Lsec21_00001048
.Lsec21_00000ff0:
    add r4, sp, #4
    ldr r1, [pc, #236]
    adds r0, r4, #0
    movs r2, #4
.Lsec21_00000ff8:
    bl memcpy
    cmp r6, #1
    beq.n .Lsec21_00001058
    movs r3, #1
    str r3, [sp, #8]
.Lsec21_00001004:
    ldrb r3, [r5, #0]
    cmp r3, #38
    beq.n .Lsec21_000010a4
    strb r3, [r4, #0]
    adds r5, #1
.Lsec21_0000100e:
    ldrb r3, [r4, #0]
    add r1, sp, #12
    strb r3, [r1, #0]
    mov r0, sl
    movs r2, #1
.Lsec21_00001018:
    bl _ZN11TiXmlString6appendEPKcj
    movs r4, #0
.Lsec21_0000101e:
    cmp r5, #0
    beq.n .Lsec21_00000f92
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00000f86
.Lsec21_00001028:
    adds r0, r5, #0
    mov r1, r8
    mov r2, r9
    adds r3, r6, #0
.Lsec21_00001030:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    bne.n .Lsec21_00000f86
    ldrb r0, [r5, #0]
    cmp r0, #13
    beq.n .Lsec21_00001042
    cmp r0, #10
    bne.n .Lsec21_00000fe4
.Lsec21_00001042:
    adds r5, #1
    movs r4, #1
    b.n .Lsec21_0000101e
.Lsec21_00001048:
    add r1, sp, #12
    movs r3, #32
    strb r3, [r1, #0]
    mov r0, sl
    movs r2, #1
.Lsec21_00001052:
    bl _ZN11TiXmlString6appendEPKcj
    b.n .Lsec21_00000ff0
.Lsec21_00001058:
    ldrb r2, [r5, #0]
    ldr r3, [pc, #120]
    lsls r2, r2, #2
    ldr r3, [r2, r3]
    str r3, [sp, #8]
    cmp r3, #4
    bhi.n .Lsec21_000010ba
.Lsec21_00001066:
    ldr r2, [sp, #8]
    cmp r2, #1
    beq.n .Lsec21_00001004
    cmp r2, #0
    beq.n .Lsec21_00001094
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_00001090
    cmp r2, #0
    ble.n .Lsec21_00001090
    movs r1, #0
    movs r0, #0
    b.n .Lsec21_00001084
.Lsec21_00001080:
    cmp r2, r1
    beq.n .Lsec21_00001090
.Lsec21_00001084:
    strb r3, [r4, r0]
    adds r1, #1
    ldrb r3, [r1, r5]
    adds r0, r1, #0
    cmp r3, #0
    bne.n .Lsec21_00001080
.Lsec21_00001090:
    adds r5, r5, r2
    b.n .Lsec21_00001098
.Lsec21_00001094:
    movs r5, #0
    movs r2, #0
.Lsec21_00001098:
    adds r1, r4, #0
    mov r0, sl
.Lsec21_0000109c:
    bl _ZN11TiXmlString6appendEPKcj
    movs r4, #0
    b.n .Lsec21_0000101e
.Lsec21_000010a4:
    adds r0, r5, #0
    add r2, sp, #8
    adds r1, r4, #0
    adds r3, r6, #0
.Lsec21_000010ac:
    bl _ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding
    ldr r2, [sp, #8]
    adds r5, r0, #0
    cmp r2, #1
    bne.n .Lsec21_00001098
    b.n .Lsec21_0000100e
.Lsec21_000010ba:
    movs r1, #167
    ldr r0, [pc, #24]
    ldr r2, [pc, #28]
    lsls r1, r1, #1
.Lsec21_000010c2:
    bl __assert
    b.n .Lsec21_00001066
    .long .Lsec49_00000000
    .long _ZN9TiXmlBase18condenseWhiteSpaceE
    .long .Lsec58_0000046c
    .long _ZN9TiXmlBase13utf8ByteTableE
    .long .Lsec49_0000011c
    .long .Lsec49_00000154
    .long .Lsec58_00000468
.thumb
.thumb_func
_ZN9TiXmlText5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    adds r5, r0, #0
    movs r0, #32
    sub sp, #20
    mov sl, r2
    adds r0, r0, r5
    movs r2, #0
    adds r6, r1, #0
    ldr r1, [pc, #260]
    adds r7, r3, #0
    mov r8, r0
.Lsec21_00001104:
    bl _ZN11TiXmlString6assignEPKcj
    adds r0, r5, #0
.Lsec21_0000110a:
    bl _ZNK9TiXmlNode11GetDocumentEv
    mov r1, sl
    mov fp, r0
    cmp r1, #0
    beq.n .Lsec21_00001128
    mov r0, sl
    adds r1, r6, #0
    adds r2, r7, #0
.Lsec21_0000111c:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    adds r3, r5, #4
    mov r2, sl
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
.Lsec21_00001128:
    movs r2, #44
    ldrb r3, [r5, r2]
    mov r9, r2
    cmp r3, #0
    bne.n .Lsec21_000011d0
    ldr r4, [pc, #212]
    adds r0, r6, #0
    adds r1, r4, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_0000113c:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_000011d8
.Lsec21_00001144:
    movs r3, #1
    mov r0, r9
    strb r3, [r5, r0]
    adds r1, r4, #0
    adds r0, r6, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_00001152:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_000011f2
    adds r5, r6, #0
    adds r5, #9
    cmp r5, #0
    beq.n .Lsec21_000011d4
    ldrb r3, [r6, #9]
    cmp r3, #0
    beq.n .Lsec21_000011d4
    mov r4, sp
    ldr r6, [pc, #160]
    adds r4, #15
    b.n .Lsec21_0000118a
.Lsec21_00001170:
    ldrb r3, [r5, #0]
    mov r0, r8
    strb r3, [r4, #0]
    adds r1, r4, #0
    movs r2, #1
    adds r5, #1
.Lsec21_0000117c:
    bl _ZN11TiXmlString6appendEPKcj
    cmp r5, #0
    beq.n .Lsec21_0000119a
    ldrb r3, [r5, #0]
    cmp r3, #0
    beq.n .Lsec21_0000119a
.Lsec21_0000118a:
    adds r0, r5, #0
    adds r1, r6, #0
    movs r2, #0
    adds r3, r7, #0
.Lsec21_00001192:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00001170
.Lsec21_0000119a:
    ldr r4, [pc, #116]
    movs r3, #0
    str r3, [sp, #0]
    adds r0, r5, #0
    add r1, sp, #8
    movs r2, #0
    adds r3, r6, #0
    str r4, [sp, #8]
    str r7, [sp, #4]
.Lsec21_000011ac:
    bl _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding
    adds r5, r0, #0
    ldr r0, [sp, #8]
    cmp r0, r4
    beq.n .Lsec21_000011c0
    cmp r0, #0
    beq.n .Lsec21_000011c0
.Lsec21_000011bc:
    bl _ZdaPv
.Lsec21_000011c0:
    adds r0, r5, #0
    add sp, #20
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_000011d0:
    ldr r4, [pc, #52]
    b.n .Lsec21_00001144
.Lsec21_000011d4:
    ldr r6, [pc, #52]
    b.n .Lsec21_0000119a
.Lsec21_000011d8:
    str r0, [sp, #0]
    ldr r3, [pc, #56]
    adds r0, r6, #0
    mov r1, r8
    movs r2, #1
    str r7, [sp, #4]
.Lsec21_000011e4:
    bl _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding
    adds r5, r0, #0
    cmp r0, #0
    beq.n .Lsec21_000011c0
    subs r5, #1
    b.n .Lsec21_000011c0
.Lsec21_000011f2:
    mov r0, fp
    movs r1, #15
    adds r2, r6, #0
    mov r3, sl
    str r7, [sp, #0]
.Lsec21_000011fc:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r5, #0
    b.n .Lsec21_000011c0
    .long .Lsec49_00000000
    .long .Lsec49_000000f0
    .long .Lsec49_00000170
    .long _ZN11TiXmlString8nullrep_E
    .long .Lsec49_00000174
.thumb
.thumb_func
_ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, sl
    mov r6, r8
    push {r6, r7}
    sub sp, #20
    adds r6, r0, #0
    adds r0, r1, #0
    adds r1, r3, #0
    adds r7, r2, #0
    adds r5, r3, #0
.Lsec21_0000122c:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    bne.n .Lsec21_00001242
.Lsec21_00001236:
    adds r0, r4, #0
    add sp, #20
    pop {r2, r3}
    mov r8, r2
    mov sl, r3
    pop {r4, r5, r6, r7, pc}
.Lsec21_00001242:
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_0000127a
    cmp r7, #0
    beq.n .Lsec21_0000125e
    adds r0, r7, #0
    adds r1, r4, #0
    adds r2, r5, #0
.Lsec21_00001252:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    adds r3, r6, #4
    adds r2, r7, #0
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
.Lsec21_0000125e:
    adds r1, r6, #0
    adds r1, #20
    adds r0, r4, #0
    adds r2, r5, #0
.Lsec21_00001266:
    bl _ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00001274
    ldrb r3, [r0, #0]
    cmp r3, #0
    bne.n .Lsec21_0000127e
.Lsec21_00001274:
    ldr r0, [r6, #16]
    cmp r0, #0
    bne.n .Lsec21_0000131c
.Lsec21_0000127a:
    movs r4, #0
    b.n .Lsec21_00001236
.Lsec21_0000127e:
    adds r1, r5, #0
.Lsec21_00001280:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r2, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00001308
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00001308
    cmp r3, #61
    bne.n .Lsec21_00001308
    adds r0, #1
    adds r1, r5, #0
.Lsec21_00001298:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    beq.n .Lsec21_00001274
    ldrb r3, [r0, #0]
    cmp r3, #0
    beq.n .Lsec21_00001274
    cmp r3, #39
    beq.n .Lsec21_00001342
    cmp r3, #34
    beq.n .Lsec21_0000132c
    movs r3, #24
    adds r3, r3, r6
    ldr r1, [pc, #148]
    adds r0, r3, #0
    movs r2, #0
    mov sl, r3
.Lsec21_000012bc:
    bl _ZN11TiXmlString6assignEPKcj
    b.n .Lsec21_000012dc
.Lsec21_000012c2:
    mov r0, r8
    cmp r0, #34
    beq.n .Lsec21_00001274
    mov r1, sp
    adds r1, #15
    strb r0, [r1, #0]
    movs r2, #1
    mov r0, sl
    adds r4, #1
.Lsec21_000012d4:
    bl _ZN11TiXmlString6appendEPKcj
    cmp r4, #0
    beq.n .Lsec21_00001236
.Lsec21_000012dc:
    ldrb r0, [r4, #0]
    mov r8, r0
    cmp r0, #0
    beq.n .Lsec21_00001236
.Lsec21_000012e4:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_00001236
    mov r1, r8
    cmp r1, #10
    beq.n .Lsec21_00001236
    cmp r1, #13
    beq.n .Lsec21_00001236
    mov r0, r8
    cmp r0, #47
    beq.n .Lsec21_00001236
    mov r3, r8
    cmp r3, #62
    beq.n .Lsec21_00001236
    cmp r3, #39
    bne.n .Lsec21_000012c2
    b.n .Lsec21_00001274
.Lsec21_00001308:
    ldr r0, [r6, #16]
    cmp r0, #0
    beq.n .Lsec21_0000127a
    movs r1, #7
    adds r3, r7, #0
    str r5, [sp, #0]
.Lsec21_00001314:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r4, #0
    b.n .Lsec21_00001236
.Lsec21_0000131c:
    adds r2, r4, #0
    movs r1, #7
    adds r3, r7, #0
    str r5, [sp, #0]
.Lsec21_00001324:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r4, #0
    b.n .Lsec21_00001236
.Lsec21_0000132c:
    adds r1, r6, #0
    ldr r3, [pc, #32]
    adds r0, #1
    adds r1, #24
.Lsec21_00001334:
    movs r2, #0
    str r2, [sp, #0]
    str r5, [sp, #4]
.Lsec21_0000133a:
    bl _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding
    adds r4, r0, #0
    b.n .Lsec21_00001236
.Lsec21_00001342:
    adds r1, r6, #0
    ldr r3, [pc, #12]
    adds r0, #1
    adds r1, #24
    b.n .Lsec21_00001334
    .long .Lsec49_00000000
    .long .Lsec49_0000017c
    .long .Lsec49_00000178
.thumb
.thumb_func
_ZN16TiXmlDeclaration5ParseEPKcP16TiXmlParsingData13TiXmlEncoding:
    push {r4, r5, r6, r7, lr}
    mov r7, fp
    mov r6, sl
    mov r5, r9
    mov r4, r8
    push {r4, r5, r6, r7}
    sub sp, #68
    adds r6, r0, #0
    adds r0, r1, #0
    adds r1, r3, #0
    mov r9, r2
    mov r8, r3
.Lsec21_00001370:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    adds r5, r0, #0
    adds r0, r6, #0
.Lsec21_00001378:
    bl _ZNK9TiXmlNode11GetDocumentEv
    adds r4, r0, #0
    cmp r5, #0
    beq.n .Lsec21_00001388
    ldrb r3, [r5, #0]
    cmp r3, #0
    bne.n .Lsec21_000013a0
.Lsec21_00001388:
    cmp r4, #0
    beq.n .Lsec21_0000138e
    b.n .Lsec21_000014e6
.Lsec21_0000138e:
    movs r7, #0
.Lsec21_00001390:
    adds r0, r7, #0
    add sp, #68
    pop {r2, r3, r4, r5}
    mov r8, r2
    mov r9, r3
    mov sl, r4
    mov fp, r5
    pop {r4, r5, r6, r7, pc}
.Lsec21_000013a0:
    ldr r1, [pc, #456]
    adds r0, r5, #0
    movs r2, #1
    mov r3, r8
.Lsec21_000013a8:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00001388
    mov r1, r9
    cmp r1, #0
    beq.n .Lsec21_000013c8
    mov r0, r9
    adds r1, r5, #0
    mov r2, r8
.Lsec21_000013bc:
    bl _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding
    adds r3, r6, #4
    mov r2, r9
    ldmia r2!, {r0, r1}
    stmia r3!, {r0, r1}
.Lsec21_000013c8:
    ldr r4, [pc, #420]
    adds r1, r6, #0
    adds r1, #44
    str r1, [sp, #12]
    adds r0, r1, #0
    movs r2, #0
    adds r1, r4, #0
.Lsec21_000013d6:
    bl _ZN11TiXmlString6assignEPKcj
    adds r2, r6, #0
    adds r2, #48
    str r2, [sp, #16]
    adds r0, r2, #0
    adds r1, r4, #0
    movs r2, #0
    adds r6, #52
.Lsec21_000013e8:
    bl _ZN11TiXmlString6assignEPKcj
    adds r7, r5, #5
    adds r0, r6, #0
    adds r1, r4, #0
    movs r2, #0
    str r6, [sp, #20]
.Lsec21_000013f6:
    bl _ZN11TiXmlString6assignEPKcj
    cmp r7, #0
    beq.n .Lsec21_00001390
    ldrb r0, [r5, #5]
    cmp r0, #0
    beq.n .Lsec21_0000138e
    cmp r0, #62
    bne.n .Lsec21_0000140a
    b.n .Lsec21_00001568
.Lsec21_0000140a:
    ldr r3, [pc, #360]
    mov fp, r3
    b.n .Lsec21_00001482
.Lsec21_00001410:
    movs r2, #1
    movs r3, #0
    negs r2, r2
    ldr r6, [pc, #352]
    ldr r5, [pc, #352]
    adds r1, r7, #0
    str r2, [sp, #36]
    str r3, [sp, #44]
    str r3, [sp, #60]
    str r3, [sp, #56]
    str r3, [sp, #40]
    str r2, [sp, #32]
    mov r3, r8
    mov r2, r9
    add r0, sp, #28
    str r5, [sp, #28]
    str r6, [sp, #52]
    str r6, [sp, #48]
.Lsec21_00001434:
    bl _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
    ldr r4, [sp, #52]
    adds r7, r0, #0
    adds r4, #8
    adds r0, r4, #0
.Lsec21_00001440:
    bl strlen
    adds r2, r0, #0
    ldr r0, [sp, #12]
.Lsec21_00001448:
    adds r1, r4, #0
.Lsec21_0000144a:
    bl _ZN11TiXmlString6assignEPKcj
    ldr r0, [sp, #52]
    str r5, [sp, #28]
    cmp r0, r6
    beq.n .Lsec21_0000145e
    cmp r0, #0
    beq.n .Lsec21_0000145e
.Lsec21_0000145a:
    bl _ZdaPv
.Lsec21_0000145e:
    ldr r0, [sp, #48]
    cmp r0, r6
    beq.n .Lsec21_0000146c
    cmp r0, #0
    beq.n .Lsec21_0000146c
.Lsec21_00001468:
    bl _ZdaPv
.Lsec21_0000146c:
    ldr r3, [pc, #272]
    str r3, [sp, #28]
.Lsec21_00001470:
    cmp r7, #0
    bne.n .Lsec21_00001476
    b.n .Lsec21_00001390
.Lsec21_00001476:
    ldrb r3, [r7, #0]
    cmp r3, #0
    bne.n .Lsec21_0000147e
    b.n .Lsec21_0000138e
.Lsec21_0000147e:
    cmp r3, #62
    beq.n .Lsec21_00001568
.Lsec21_00001482:
    adds r0, r7, #0
    mov r1, r8
.Lsec21_00001486:
    bl _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding
    mov r1, fp
    movs r2, #1
    mov r3, r8
    adds r7, r0, #0
.Lsec21_00001492:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    adds r4, r0, #0
    cmp r0, #0
    bne.n .Lsec21_00001410
    ldr r1, [pc, #228]
    adds r0, r7, #0
    movs r2, #1
    mov r3, r8
.Lsec21_000014a4:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    mov sl, r0
    cmp r0, #0
    beq.n .Lsec21_000014fa
    movs r3, #1
    negs r3, r3
    ldr r6, [pc, #196]
    ldr r5, [pc, #196]
    adds r1, r7, #0
    mov r2, r9
    str r3, [sp, #36]
    str r3, [sp, #32]
    add r0, sp, #28
    mov r3, r8
    str r4, [sp, #44]
    str r4, [sp, #60]
    str r4, [sp, #56]
    str r4, [sp, #40]
    str r5, [sp, #28]
    str r6, [sp, #52]
    str r6, [sp, #48]
.Lsec21_000014d0:
    bl _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
    ldr r4, [sp, #52]
    adds r7, r0, #0
    adds r4, #8
    adds r0, r4, #0
.Lsec21_000014dc:
    bl strlen
    adds r2, r0, #0
    ldr r0, [sp, #16]
    b.n .Lsec21_00001448
.Lsec21_000014e6:
    mov r0, r8
    str r0, [sp, #0]
    movs r1, #12
    adds r0, r4, #0
    movs r2, #0
    movs r3, #0
.Lsec21_000014f2:
    bl _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding
    movs r7, #0
    b.n .Lsec21_00001390
.Lsec21_000014fa:
    ldr r1, [pc, #140]
    adds r0, r7, #0
    movs r2, #1
    mov r3, r8
.Lsec21_00001502:
    bl _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding
    cmp r0, #0
    beq.n .Lsec21_00001562
    movs r3, #1
    mov r0, sl
    negs r3, r3
    ldr r6, [pc, #100]
    ldr r5, [pc, #104]
    adds r1, r7, #0
    mov r2, r9
    str r3, [sp, #36]
    str r0, [sp, #44]
    str r0, [sp, #60]
    str r0, [sp, #56]
    str r0, [sp, #40]
    str r3, [sp, #32]
    add r0, sp, #28
    mov r3, r8
    str r5, [sp, #28]
    str r6, [sp, #52]
    str r6, [sp, #48]
.Lsec21_0000152e:
    bl _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
    ldr r4, [sp, #52]
    adds r7, r0, #0
    adds r4, #8
    adds r0, r4, #0
.Lsec21_0000153a:
    bl strlen
    adds r2, r0, #0
    ldr r0, [sp, #20]
    b.n .Lsec21_00001448
.Lsec21_00001544:
    ldrb r4, [r7, #0]
    cmp r4, #0
    beq.n .Lsec21_00001470
    cmp r4, #62
    beq.n .Lsec21_00001470
    adds r0, r4, #0
.Lsec21_00001550:
    bl isspace
    cmp r0, #0
    bne.n .Lsec21_00001470
    cmp r4, #10
    beq.n .Lsec21_00001470
    cmp r4, #13
    beq.n .Lsec21_00001470
    adds r7, #1
.Lsec21_00001562:
    cmp r7, #0
    bne.n .Lsec21_00001544
    b.n .Lsec21_00001390
.Lsec21_00001568:
    adds r7, #1
    b.n .Lsec21_00001390
    .long .Lsec49_000000e8
    .long .Lsec49_00000000
    .long .Lsec49_00000180
    .long _ZN11TiXmlString8nullrep_E
    .long _ZTV14TiXmlAttribute + 0x8
    .long _ZTV9TiXmlBase + 0x8
    .long .Lsec49_00000188
    .long .Lsec49_00000194

.section .data,"aw",%progbits
.balign 4
_ZN9TiXmlBase6entityE:
    .long .Lsec49_000001a0
    .long 0x00000005
    .long 0x00000026
    .long .Lsec49_000001a8
    .long 0x00000004
    .long 0x0000003c
    .long .Lsec49_000001b0
    .long 0x00000004
    .long 0x0000003e
    .long .Lsec49_000001b8
    .long 0x00000006
    .long 0x00000022
    .long .Lsec49_000001c0
    .long 0x00000006
    .long 0x00000027

.section .bss,"aw",%nobits
.balign 1

.section .text._ZNK9TiXmlNode9ToElementEv,"axG",%progbits,_ZNK9TiXmlNode9ToElementEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK9TiXmlNode9ToElementEv:
    movs r0, #0
    bx lr

.section .text._ZNK9TiXmlNode9ToCommentEv,"axG",%progbits,_ZNK9TiXmlNode9ToCommentEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK9TiXmlNode9ToCommentEv:
    movs r0, #0
    bx lr

.section .text._ZNK9TiXmlNode9ToUnknownEv,"axG",%progbits,_ZNK9TiXmlNode9ToUnknownEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK9TiXmlNode9ToUnknownEv:
    movs r0, #0
    bx lr

.section .text._ZNK9TiXmlNode6ToTextEv,"axG",%progbits,_ZNK9TiXmlNode6ToTextEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK9TiXmlNode6ToTextEv:
    movs r0, #0
    bx lr

.section .text._ZNK9TiXmlNode13ToDeclarationEv,"axG",%progbits,_ZNK9TiXmlNode13ToDeclarationEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK9TiXmlNode13ToDeclarationEv:
    movs r0, #0
    bx lr

.section .text._ZN9TiXmlNode9ToElementEv,"axG",%progbits,_ZN9TiXmlNode9ToElementEv,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlNode9ToElementEv:
    movs r0, #0
    bx lr

.section .text._ZN9TiXmlNode9ToCommentEv,"axG",%progbits,_ZN9TiXmlNode9ToCommentEv,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlNode9ToCommentEv:
    movs r0, #0
    bx lr

.section .text._ZN9TiXmlNode9ToUnknownEv,"axG",%progbits,_ZN9TiXmlNode9ToUnknownEv,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlNode9ToUnknownEv:
    movs r0, #0
    bx lr

.section .text._ZN9TiXmlNode6ToTextEv,"axG",%progbits,_ZN9TiXmlNode6ToTextEv,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlNode6ToTextEv:
    movs r0, #0
    bx lr

.section .text._ZN9TiXmlNode13ToDeclarationEv,"axG",%progbits,_ZN9TiXmlNode13ToDeclarationEv,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlNode13ToDeclarationEv:
    movs r0, #0
    bx lr

.section .text._ZNK13TiXmlDocument10ToDocumentEv,"axG",%progbits,_ZNK13TiXmlDocument10ToDocumentEv,comdat
.balign 4
.thumb
.thumb_func
_ZNK13TiXmlDocument10ToDocumentEv:
    bx lr
    mov r8, r8

.section .text._ZN13TiXmlDocument10ToDocumentEv,"axG",%progbits,_ZN13TiXmlDocument10ToDocumentEv,comdat
.balign 4
.thumb
.thumb_func
_ZN13TiXmlDocument10ToDocumentEv:
    bx lr
    mov r8, r8

.section .text._ZNK14TiXmlAttribute5PrintEP7__sFILEi,"axG",%progbits,_ZNK14TiXmlAttribute5PrintEP7__sFILEi,comdat
.balign 4
.thumb
.thumb_func
_ZNK14TiXmlAttribute5PrintEP7__sFILEi:
    push {lr}
    sub sp, #4
    movs r3, #0
.Lsec43_00000006:
    bl _ZNK14TiXmlAttribute5PrintEP7__sFILEiP11TiXmlString
    add sp, #4
    pop {pc}
    mov r8, r8

.section .text._ZN9TiXmlBaseD0Ev,"axG",%progbits,_ZN9TiXmlBaseD0Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlBaseD0Ev:
    push {r4, lr}
    ldr r3, [pc, #12]
    adds r4, r0, #0
    str r3, [r0, #0]
.Lsec45_00000008:
    bl _ZdlPv
    adds r0, r4, #0
    pop {r4, pc}
    .long _ZTV9TiXmlBase + 0x8

.section .text._ZN9TiXmlBaseD1Ev,"axG",%progbits,_ZN9TiXmlBaseD1Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN9TiXmlBaseD1Ev:
    ldr r3, [pc, #4]
    str r3, [r0, #0]
    bx lr
    lsls r0, r0, #0
    .long _ZTV9TiXmlBase + 0x8

.section .rodata.str1.4,"aMS",%progbits,1
.balign 4
.Lsec49_00000000:
    .asciz ""
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_00000004:
    .asciz "/home/tob/coding/dsdev/tob/tinyxml/source/tinyxmlparser.cpp"
.Lsec49_00000040:
    .asciz "now"
.Lsec49_00000044:
    .asciz "p"
    .asciz ""
    .asciz ""
.Lsec49_00000048:
    .asciz "cursor.row >= -1"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_0000005c:
    .asciz "cursor.col >= -1"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_00000070:
    .asciz "stamp"
    .asciz ""
    .asciz ""
.Lsec49_00000078:
    .asciz "strlen( entity[i].str ) == entity[i].strLength"
    .asciz ""
.Lsec49_000000a8:
    .asciz "tag"
.Lsec49_000000ac:
    .asciz "0"
    .asciz ""
    .asciz ""
.Lsec49_000000b0:
    .asciz "err > 0 && err < TIXML_ERROR_STRING_COUNT"
    .asciz ""
    .asciz ""
.Lsec49_000000dc:
    .asciz "<!--"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_000000e4:
    .asciz "-->"
.Lsec49_000000e8:
    .asciz "<?xml"
    .asciz ""
    .asciz ""
.Lsec49_000000f0:
    .asciz "<![CDATA["
    .asciz ""
    .asciz ""
.Lsec49_000000fc:
    .asciz "<!"
    .asciz ""
.Lsec49_00000100:
    .asciz "</"
    .asciz ""
.Lsec49_00000104:
    .asciz ">"
    .asciz ""
    .asciz ""
.Lsec49_00000108:
    .asciz "enc"
.Lsec49_0000010c:
    .asciz "UTF-8"
    .asciz ""
    .asciz ""
.Lsec49_00000114:
    .asciz "UTF8"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_0000011c:
    .asciz "/home/tob/coding/dsdev/tob/tinyxml/include/tinyxml.h"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_00000154:
    .asciz "*length >= 0 && *length < 5"
.Lsec49_00000170:
    .asciz "]]>"
.Lsec49_00000174:
    .asciz "<"
    .asciz ""
    .asciz ""
.Lsec49_00000178:
    .asciz "'"
    .asciz ""
    .asciz ""
.Lsec49_0000017c:
    .asciz "\""
    .asciz ""
    .asciz ""
.Lsec49_00000180:
    .asciz "version"
.Lsec49_00000188:
    .asciz "encoding"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_00000194:
    .asciz "standalone"
    .asciz ""
.Lsec49_000001a0:
    .asciz "&amp;"
    .asciz ""
    .asciz ""
.Lsec49_000001a8:
    .asciz "&lt;"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_000001b0:
    .asciz "&gt;"
    .asciz ""
    .asciz ""
    .asciz ""
.Lsec49_000001b8:
    .asciz "&quot;"
    .asciz ""
.Lsec49_000001c0:
    .asciz "&apos;"
    .asciz ""

.section .text._ZN14TiXmlAttributeD1Ev,"axG",%progbits,_ZN14TiXmlAttributeD1Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN14TiXmlAttributeD1Ev:
    push {r4, r5, lr}
    ldr r3, [pc, #48]
    adds r4, r0, #0
    str r3, [r0, #0]
    ldr r5, [pc, #44]
    ldr r0, [r0, #24]
    sub sp, #4
    cmp r0, r5
    beq.n .Lsec50_0000001a
    cmp r0, #0
    beq.n .Lsec50_0000001a
.Lsec50_00000016:
    bl _ZdaPv
.Lsec50_0000001a:
    ldr r0, [r4, #20]
    cmp r0, r5
    beq.n .Lsec50_00000028
    cmp r0, #0
    beq.n .Lsec50_00000028
.Lsec50_00000024:
    bl _ZdaPv
.Lsec50_00000028:
    ldr r3, [pc, #16]
    adds r0, r4, #0
    add sp, #4
    str r3, [r4, #0]
    pop {r4, r5, pc}
    lsls r0, r0, #0
    .long _ZTV14TiXmlAttribute + 0x8
    .long _ZN11TiXmlString8nullrep_E
    .long _ZTV9TiXmlBase + 0x8

.section .text._ZN14TiXmlAttributeD0Ev,"axG",%progbits,_ZN14TiXmlAttributeD0Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN14TiXmlAttributeD0Ev:
    push {r4, r5, lr}
    ldr r3, [pc, #52]
    adds r4, r0, #0
    str r3, [r0, #0]
    ldr r5, [pc, #48]
    ldr r0, [r0, #24]
    sub sp, #4
    cmp r0, r5
    beq.n .Lsec52_0000001a
    cmp r0, #0
    beq.n .Lsec52_0000001a
.Lsec52_00000016:
    bl _ZdaPv
.Lsec52_0000001a:
    ldr r0, [r4, #20]
    cmp r0, r5
    beq.n .Lsec52_00000028
    cmp r0, #0
    beq.n .Lsec52_00000028
.Lsec52_00000024:
    bl _ZdaPv
.Lsec52_00000028:
    ldr r3, [pc, #20]
    adds r0, r4, #0
    str r3, [r4, #0]
.Lsec52_0000002e:
    bl _ZdlPv
    adds r0, r4, #0
    add sp, #4
    pop {r4, r5, pc}
    .long _ZTV14TiXmlAttribute + 0x8
    .long _ZN11TiXmlString8nullrep_E
    .long _ZTV9TiXmlBase + 0x8

.section .text._ZN13TiXmlDocumentD0Ev,"axG",%progbits,_ZN13TiXmlDocumentD0Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN13TiXmlDocumentD0Ev:
    push {r4, lr}
    ldr r3, [pc, #36]
    adds r4, r0, #0
    str r3, [r0, #0]
    ldr r0, [r0, #52]
    ldr r3, [pc, #32]
    cmp r0, r3
    beq.n .Lsec54_00000018
    cmp r0, #0
    beq.n .Lsec54_00000018
.Lsec54_00000014:
    bl _ZdaPv
.Lsec54_00000018:
    adds r0, r4, #0
.Lsec54_0000001a:
    bl _ZN9TiXmlNodeD2Ev
    adds r0, r4, #0
.Lsec54_00000020:
    bl _ZdlPv
    adds r0, r4, #0
    pop {r4, pc}
    .long _ZTV13TiXmlDocument + 0x8
    .long _ZN11TiXmlString8nullrep_E

.section .text._ZN13TiXmlDocumentD1Ev,"axG",%progbits,_ZN13TiXmlDocumentD1Ev,comdat
.balign 4
.thumb
.thumb_func
_ZN13TiXmlDocumentD1Ev:
    push {r4, lr}
    ldr r3, [pc, #32]
    adds r4, r0, #0
    str r3, [r0, #0]
    ldr r0, [r0, #52]
    ldr r3, [pc, #28]
    cmp r0, r3
    beq.n .Lsec56_00000018
    cmp r0, #0
    beq.n .Lsec56_00000018
.Lsec56_00000014:
    bl _ZdaPv
.Lsec56_00000018:
    adds r0, r4, #0
.Lsec56_0000001a:
    bl _ZN9TiXmlNodeD2Ev
    adds r0, r4, #0
    pop {r4, pc}
    lsls r0, r0, #0
    .long _ZTV13TiXmlDocument + 0x8
    .long _ZN11TiXmlString8nullrep_E

.section .rodata,"a",%progbits
.balign 8
_ZN9TiXmlBase13utf8ByteTableE:
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000002
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000003
    .long 0x00000004
    .long 0x00000004
    .long 0x00000004
    .long 0x00000004
    .long 0x00000004
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
    .long 0x00000001
_ZTV13TiXmlDocument:
    .long 0x00000000
    .long 0x00000000
    .long _ZN13TiXmlDocumentD1Ev
    .long _ZN13TiXmlDocumentD0Ev
    .long _ZNK13TiXmlDocument5PrintEP7__sFILEi
    .long _ZN13TiXmlDocument5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
    .long _ZNK13TiXmlDocument10ToDocumentEv
    .long _ZNK9TiXmlNode9ToElementEv
    .long _ZNK9TiXmlNode9ToCommentEv
    .long _ZNK9TiXmlNode9ToUnknownEv
    .long _ZNK9TiXmlNode6ToTextEv
    .long _ZNK9TiXmlNode13ToDeclarationEv
    .long _ZN13TiXmlDocument10ToDocumentEv
    .long _ZN9TiXmlNode9ToElementEv
    .long _ZN9TiXmlNode9ToCommentEv
    .long _ZN9TiXmlNode9ToUnknownEv
    .long _ZN9TiXmlNode6ToTextEv
    .long _ZN9TiXmlNode13ToDeclarationEv
    .long _ZNK13TiXmlDocument5CloneEv
    .long _ZNK13TiXmlDocument6AcceptEP12TiXmlVisitor
_ZTV14TiXmlAttribute:
    .long 0x00000000
    .long 0x00000000
    .long _ZN14TiXmlAttributeD1Ev
    .long _ZN14TiXmlAttributeD0Ev
    .long _ZNK14TiXmlAttribute5PrintEP7__sFILEi
    .long _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding
_ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.68:
.Lsec58_00000468:
    .long 0x00000000
_ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.62:
.Lsec58_0000046c:
    .long 0x00000000
FIRST_BYTE_MARK.5676:
.Lsec58_00000470:
    .long 0x00000000
    .long 0x00000000
    .long 0x000000c0
    .long 0x000000e0
    .long 0x000000f0
    .long 0x000000f8
    .long 0x000000fc
    .long 0x00000000

.section .rodata._ZTV9TiXmlBase,"aG",%progbits,_ZTV9TiXmlBase,comdat
.balign 8
_ZTV9TiXmlBase:
    .long 0x00000000
    .long 0x00000000
    .long _ZN9TiXmlBaseD1Ev
    .long _ZN9TiXmlBaseD0Ev
    .long __cxa_pure_virtual
    .long __cxa_pure_virtual

.size FIRST_BYTE_MARK.5676, 28
.size _ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.62, 4
.size _ZZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncodingE4C.68, 4
.size _ZNK9TiXmlNode9ToElementEv, 4
.size _ZNK9TiXmlNode9ToCommentEv, 4
.size _ZNK9TiXmlNode9ToUnknownEv, 4
.size _ZNK9TiXmlNode6ToTextEv, 4
.size _ZNK9TiXmlNode13ToDeclarationEv, 4
.size _ZN9TiXmlNode9ToElementEv, 4
.size _ZN9TiXmlNode9ToCommentEv, 4
.size _ZN9TiXmlNode9ToUnknownEv, 4
.size _ZN9TiXmlNode6ToTextEv, 4
.size _ZN9TiXmlNode13ToDeclarationEv, 4
.size _ZNK13TiXmlDocument10ToDocumentEv, 2
.size _ZN13TiXmlDocument10ToDocumentEv, 2
.size _ZN9TiXmlBase18ConvertUTF32ToUTF8EmPcPi, 140
.size _ZNK14TiXmlAttribute5PrintEP7__sFILEi, 14
.size _ZN9TiXmlBaseD0Ev, 20
.size _ZTV9TiXmlBase, 24
.size _ZN9TiXmlBaseD1Ev, 12
.size _ZN16TiXmlParsingData5StampEPKc13TiXmlEncoding, 332
.size _ZN9TiXmlBase13utf8ByteTableE, 1024
.size _ZNK9TiXmlText5BlankEv, 48
.size _ZN9TiXmlBase10IsAlphaNumEh13TiXmlEncoding, 20
.size _ZN9TiXmlBase7IsAlphaEh13TiXmlEncoding, 20
.size _ZN14TiXmlAttributeD1Ev, 64
.size _ZTV14TiXmlAttribute, 24
.size _ZN9TiXmlBase9GetEntityEPKcPcPi13TiXmlEncoding, 416
.size _ZN9TiXmlBase6entityE, 60
.size _ZN14TiXmlAttributeD0Ev, 68
.size _ZN13TiXmlDocumentD0Ev, 48
.size _ZTV13TiXmlDocument, 80
.size _ZN9TiXmlBase11StringEqualEPKcS1_b13TiXmlEncoding, 220
.size _ZN13TiXmlDocumentD1Ev, 44
.size _ZN9TiXmlBase14SkipWhiteSpaceEPKc13TiXmlEncoding, 118
.size _ZN9TiXmlBase8ReadNameEPKcP11TiXmlString13TiXmlEncoding, 148
.size _ZN13TiXmlDocument8SetErrorEiPKcP16TiXmlParsingData13TiXmlEncoding, 144
.size _ZN12TiXmlComment5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 212
.size _ZN12TiXmlUnknown5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 196
.size _ZN9TiXmlNode8IdentifyEPKc13TiXmlEncoding, 356
.size _ZN12TiXmlElement9ReadValueEPKcP16TiXmlParsingData13TiXmlEncoding, 320
.size _ZN12TiXmlElement5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 676
.size _ZN13TiXmlDocument5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 412
.size _ZN9TiXmlBase8ReadTextEPKcP11TiXmlStringbS1_b13TiXmlEncoding, 544
.size _ZN9TiXmlText5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 308
.size _ZN14TiXmlAttribute5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 320
.size _ZN16TiXmlDeclaration5ParseEPKcP16TiXmlParsingData13TiXmlEncoding, 564

.section .note.GNU-stack,"",%progbits
